name = "mdforagents-worker"
main = "src/index.ts"
compatibility_date = "2026-07-26"

routes = [
  { pattern = "allto.agentok.top", custom_domain = true }
]

[vars]
APP_NAME = "mdforagents"

[assets]
directory = "../web/dist"
binding = "ASSETS"

[build]
command = "pnpm build"

[[d1_databases]]
binding = "DB"
database_name = "mdforagents"
database_id = "7478e1ef-3a30-4abf-9184-29a0cc4785ed"
