import type { Language } from './i18n';
import type { ToolSeoCopy, ToolSeoSlug } from './ToolSeoContent';

export type AddedToolSeoSlug = 'markdown-to-html' | 'markdown-to-pdf' | 'markdown-to-word' | 'markdown-to-csv' | 'markdown-to-wechat' | 'markdown-to-xiaohongshu' | 'merge-pptx' | 'merge-excel';

type Profile = {
  name: string;
  input: string;
  output: string;
  workflow: string;
  detail: string;
  limit: string;
  faq: string;
  related: Array<{ label: string; path: string }>;
};

const profiles: Record<AddedToolSeoSlug, Record<Language, Profile>> = {
  'markdown-to-html': {
    zh: { name: 'Markdown转HTML', input: 'Markdown文字或.md文件', output: '可独立打开的.html文件', workflow: '先查看HTML预览，再下载独立文件。', detail: '支持标题、段落、列表、表格、链接、代码块和图片等常用Markdown内容。', limit: '外部图片、字体和编辑器专属扩展可能受浏览器权限影响。', faq: '下载的HTML包含文章内容和基础样式，可以保存后直接用浏览器打开。', related: [{ label: 'Markdown转PDF', path: '/markdown-to-pdf' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    en: { name: 'Markdown to HTML', input: 'Markdown text or a .md file', output: 'a standalone .html file', workflow: 'Review the HTML preview, then download the standalone file.', detail: 'Common headings, paragraphs, lists, tables, links, code blocks, and images are rendered in the browser.', limit: 'Remote images, fonts, and editor-specific extensions may be limited by browser permissions.', faq: 'The downloaded HTML includes the rendered article and basic styles, so it can be opened directly in a browser.', related: [{ label: 'Markdown to PDF', path: '/markdown-to-pdf' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    ja: { name: 'MarkdownからHTMLへ', input: 'Markdownテキストまたは.mdファイル', output: '単独で開ける.htmlファイル', workflow: 'HTMLプレビューを確認してから単独ファイルを保存します。', detail: '見出し、段落、リスト、表、リンク、コード、画像などの一般的なMarkdownを表示します。', limit: '外部画像、フォント、エディター固有の拡張はブラウザ権限の影響を受ける場合があります。', faq: '出力HTMLには記事と基本スタイルが含まれるため、保存後にブラウザで直接開けます。', related: [{ label: 'MarkdownからPDFへ', path: '/markdown-to-pdf' }, { label: 'Markdownビューア', path: '/markdown-viewer' }] },
    es: { name: 'Markdown a HTML', input: 'Texto Markdown o un archivo .md', output: 'un archivo .html independiente', workflow: 'Revisa la vista previa HTML y descarga el archivo independiente.', detail: 'Renderiza títulos, párrafos, listas, tablas, enlaces, bloques de código e imágenes habituales.', limit: 'Las imágenes remotas, fuentes y extensiones del editor pueden depender de los permisos del navegador.', faq: 'El HTML descargado incluye el artículo renderizado y estilos básicos, por lo que puede abrirse directamente.', related: [{ label: 'Markdown a PDF', path: '/markdown-to-pdf' }, { label: 'Visor Markdown', path: '/markdown-viewer' }] },
    de: { name: 'Markdown zu HTML', input: 'Markdown-Text oder eine .md-Datei', output: 'eine eigenständige .html-Datei', workflow: 'HTML-Vorschau prüfen und anschließend die eigenständige Datei laden.', detail: 'Übliche Überschriften, Absätze, Listen, Tabellen, Links, Codeblöcke und Bilder werden gerendert.', limit: 'Remote-Bilder, Schriften und editorbezogene Erweiterungen können durch Browserrechte begrenzt sein.', faq: 'Die geladene HTML-Datei enthält den gerenderten Artikel und grundlegende Styles und kann direkt geöffnet werden.', related: [{ label: 'Markdown zu PDF', path: '/markdown-to-pdf' }, { label: 'Markdown-Viewer', path: '/markdown-viewer' }] },
  },
  'markdown-to-pdf': {
    zh: { name: 'Markdown转PDF', input: 'Markdown文字或.md文件', output: '适合打印和分享的A4PDF', workflow: '检查分页、表格和代码块，点击打印/保存PDF后在打印窗口中选择保存为PDF。', detail: '当前预览会按A4页面排版，适合报告、说明文档、学习笔记和交付资料。', limit: '复杂分页、外部字体、远程图片和超长代码块可能需要打印预览后复核。', faq: '点击打印/保存PDF后会打开浏览器打印窗口，选择保存为PDF即可。标题、列表、表格、代码和链接会尽量保留。', related: [{ label: 'Markdown转HTML', path: '/markdown-to-html' }, { label: 'Markdown转Word', path: '/markdown-to-word' }] },
    en: { name: 'Markdown to PDF', input: 'Markdown text or a .md file', output: 'an A4 PDF for sharing or printing', workflow: 'Check page breaks, tables, and code blocks, then click Print/Save PDF and choose Save as PDF in the print dialog.', detail: 'The current preview is formatted for A4 pages and suits reports, notes, manuals, and delivery documents.', limit: 'Complex page breaks, external fonts, remote images, and very long code blocks may need a final review in print preview.', faq: 'Click Print/Save PDF to open the browser print dialog, then choose Save as PDF. Headings, lists, tables, code, and links are preserved where possible.', related: [{ label: 'Markdown to HTML', path: '/markdown-to-html' }, { label: 'Markdown to Word', path: '/markdown-to-word' }] },
    ja: { name: 'MarkdownからPDFへ', input: 'Markdownテキストまたは.mdファイル', output: '共有や印刷に使えるA4 PDF', workflow: '改ページ、表、コードを確認し、印刷またはPDF保存をクリックして印刷画面でPDFとして保存します。', detail: '現在のプレビューをA4向けに整え、レポート、ノート、説明書、納品資料に利用できます。', limit: '複雑な改ページ、外部フォント、外部画像、長いコードは印刷プレビューで確認してください。', faq: '印刷またはPDF保存をクリックするとブラウザの印刷画面が開きます。PDFとして保存を選ぶと、見出し、表、コード、リンクを可能な範囲で保持できます。', related: [{ label: 'MarkdownからHTMLへ', path: '/markdown-to-html' }, { label: 'MarkdownからWordへ', path: '/markdown-to-word' }] },
    es: { name: 'Markdown a PDF', input: 'Texto Markdown o un archivo .md', output: 'un PDF A4 para compartir o imprimir', workflow: 'Comprueba saltos de página, tablas y código, pulsa Imprimir o guardar PDF y elige Guardar como PDF.', detail: 'La vista actual se formatea para páginas A4 y sirve para informes, notas, manuales y documentos de entrega.', limit: 'Los saltos complejos, fuentes externas, imágenes remotas y bloques de código largos pueden necesitar revisión en la vista de impresión.', faq: 'Pulsa Imprimir o guardar PDF para abrir la ventana de impresión del navegador y elige Guardar como PDF. Se conservan títulos, listas, tablas, código y enlaces cuando es posible.', related: [{ label: 'Markdown a HTML', path: '/markdown-to-html' }, { label: 'Markdown a Word', path: '/markdown-to-word' }] },
    de: { name: 'Markdown zu PDF', input: 'Markdown-Text oder eine .md-Datei', output: 'eine A4-PDF zum Teilen oder Drucken', workflow: 'Seitenumbrüche, Tabellen und Code prüfen, PDF drucken oder speichern klicken und im Druckdialog Als PDF speichern wählen.', detail: 'Die aktuelle Vorschau wird für A4 formatiert und eignet sich für Berichte, Notizen, Handbücher und Lieferdokumente.', limit: 'Komplexe Seitenumbrüche, externe Schriften, Remote-Bilder und sehr lange Codeblöcke müssen eventuell in der Druckvorschau geprüft werden.', faq: 'PDF drucken oder speichern öffnet den Browser-Druckdialog. Wähle Als PDF speichern; Überschriften, Listen, Tabellen, Code und Links bleiben möglichst erhalten.', related: [{ label: 'Markdown zu HTML', path: '/markdown-to-html' }, { label: 'Markdown zu Word', path: '/markdown-to-word' }] },
  },
  'markdown-to-word': {
    zh: { name: 'Markdown转Word', input: 'Markdown文字或.md文件', output: '可继续编辑的.docx文档', workflow: '查看结构预览，确认标题和表格后下载Word文档。', detail: '适合把AI生成内容、技术笔记和报告草稿交给Word继续审阅和编辑。', limit: '批注、修订、复杂主题、嵌入对象和特殊字体不会完整复制。', faq: '输出是标准DOCX文件，可以在Microsoft Word、LibreOffice和兼容办公软件中继续编辑。', related: [{ label: 'Word转Markdown', path: '/word-to-markdown' }, { label: 'Markdown转PDF', path: '/markdown-to-pdf' }] },
    en: { name: 'Markdown to Word', input: 'Markdown text or a .md file', output: 'an editable .docx document', workflow: 'Review the structure preview, check headings and tables, then download Word.', detail: 'Useful when AI output, technical notes, or report drafts need review and editing in Word.', limit: 'Comments, tracked changes, complex themes, embedded objects, and special fonts are not fully reproduced.', faq: 'The result is a standard DOCX file that can continue in Microsoft Word, LibreOffice, and compatible office software.', related: [{ label: 'Word to Markdown', path: '/word-to-markdown' }, { label: 'Markdown to PDF', path: '/markdown-to-pdf' }] },
    ja: { name: 'MarkdownからWordへ', input: 'Markdownテキストまたは.mdファイル', output: '編集可能な.docx文書', workflow: '構造プレビューを確認し、見出しと表を確認してWordを保存します。', detail: 'AIの下書き、技術メモ、レポートをWordでレビューや編集するときに便利です。', limit: 'コメント、変更履歴、複雑なテーマ、埋め込みオブジェクト、特殊フォントは完全には再現されません。', faq: '標準的なDOCXとして出力され、Microsoft Word、LibreOfficeなどで続けて編集できます。', related: [{ label: 'WordからMarkdown', path: '/word-to-markdown' }, { label: 'MarkdownからPDFへ', path: '/markdown-to-pdf' }] },
    es: { name: 'Markdown a Word', input: 'Texto Markdown o un archivo .md', output: 'un documento .docx editable', workflow: 'Revisa la estructura, comprueba títulos y tablas y descarga el documento Word.', detail: 'Sirve para revisar y editar en Word contenidos generados por IA, notas técnicas y borradores de informes.', limit: 'Los comentarios, cambios controlados, temas complejos, objetos incrustados y fuentes especiales no se reproducen por completo.', faq: 'El resultado es un DOCX estándar que puede seguir editándose en Microsoft Word, LibreOffice y programas compatibles.', related: [{ label: 'Word a Markdown', path: '/word-to-markdown' }, { label: 'Markdown a PDF', path: '/markdown-to-pdf' }] },
    de: { name: 'Markdown zu Word', input: 'Markdown-Text oder eine .md-Datei', output: 'ein bearbeitbares .docx-Dokument', workflow: 'Strukturvorschau sowie Überschriften und Tabellen prüfen und Word laden.', detail: 'Geeignet, wenn AI-Inhalte, technische Notizen oder Berichtsentwürfe in Word geprüft und bearbeitet werden sollen.', limit: 'Kommentare, Änderungsverfolgung, komplexe Designs, eingebettete Objekte und Spezialschriften werden nicht vollständig übernommen.', faq: 'Das Ergebnis ist eine Standard-DOCX-Datei und kann in Microsoft Word, LibreOffice und kompatibler Software weiterbearbeitet werden.', related: [{ label: 'Word zu Markdown', path: '/word-to-markdown' }, { label: 'Markdown zu PDF', path: '/markdown-to-pdf' }] },
  },
  'markdown-to-csv': {
    zh: { name: 'Markdown转CSV', input: '包含标准分隔线的Markdown表格', output: '可在Excel中打开的CSV文件', workflow: '确认检测到的表格和列数，再下载CSV。', detail: '适合把Markdown中的数据表交给Excel、表格软件或数据分析工具继续处理。', limit: '当前导出第一个Markdown表格，不会把普通段落或无分隔线的伪表格当成数据表。', faq: '页面会从Markdown中识别带分隔线的标准表格，并将第一个表格导出为CSV。', related: [{ label: 'CSV转Markdown', path: '/csv-to-markdown' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    en: { name: 'Markdown to CSV', input: 'A Markdown table with a separator row', output: 'a CSV file for Excel or data tools', workflow: 'Check the detected table and columns, then download the CSV.', detail: 'Useful for moving a Markdown data table into Excel, spreadsheet software, or a data workflow.', limit: 'The current export uses the first standard Markdown table and does not treat paragraphs or informal grids as tables.', faq: 'The page detects a standard table with a separator row and exports the first detected table as CSV.', related: [{ label: 'CSV to Markdown', path: '/csv-to-markdown' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    ja: { name: 'MarkdownからCSVへ', input: '区切り行のあるMarkdown表', output: 'Excelやデータツール用のCSV', workflow: '検出された表と列を確認してCSVを保存します。', detail: 'Markdownのデータ表をExcel、表計算ソフト、データ処理へ移すときに使えます。', limit: '最初の標準Markdown表を出力します。段落や区切り行のない疑似表は対象外です。', faq: '区切り行のある標準表を検出し、最初に見つかった表をCSVとして出力します。', related: [{ label: 'CSVからMarkdown', path: '/csv-to-markdown' }, { label: 'Markdownビューア', path: '/markdown-viewer' }] },
    es: { name: 'Markdown a CSV', input: 'Una tabla Markdown con fila separadora', output: 'un CSV para Excel o herramientas de datos', workflow: 'Comprueba la tabla y las columnas detectadas y descarga el CSV.', detail: 'Permite llevar una tabla de datos Markdown a Excel, una hoja de cálculo o un flujo de datos.', limit: 'La exportación usa la primera tabla Markdown estándar y no convierte párrafos ni cuadrículas informales.', faq: 'Detecta una tabla estándar con fila separadora y exporta como CSV la primera tabla encontrada.', related: [{ label: 'CSV a Markdown', path: '/csv-to-markdown' }, { label: 'Visor Markdown', path: '/markdown-viewer' }] },
    de: { name: 'Markdown zu CSV', input: 'Eine Markdown-Tabelle mit Trennzeile', output: 'eine CSV für Excel oder Datentools', workflow: 'Erkannte Tabelle und Spalten prüfen und danach die CSV laden.', detail: 'Damit lassen sich Markdown-Datentabellen in Excel, Tabellenkalkulationen oder Datenabläufe übernehmen.', limit: 'Exportiert wird die erste standardkonforme Markdown-Tabelle; Absätze und informelle Raster zählen nicht als Tabellen.', faq: 'Eine Standardtabelle mit Trennzeile wird erkannt und die erste gefundene Tabelle als CSV exportiert.', related: [{ label: 'CSV zu Markdown', path: '/csv-to-markdown' }, { label: 'Markdown-Viewer', path: '/markdown-viewer' }] },
  },
  'markdown-to-wechat': {
    zh: { name: 'Markdown转微信公众号', input: '包含标题、列表、引用、表格或代码的Markdown', output: '可复制到公众号编辑器的富文本', workflow: '选择主题，检查手机预览，再复制到公众号编辑器。', detail: '复制时同时提供HTML和纯文本，适合从Obsidian、VSCode或其他Markdown编辑器发布文章。', limit: '公众号编辑器对外部图片、复杂CSS、动态组件和部分代码样式有自己的限制。', faq: '复制按钮会写入富文本和纯文本两种格式，粘贴到公众号编辑器后可以继续调整。', related: [{ label: 'Markdown转小红书', path: '/markdown-to-xiaohongshu' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    en: { name: 'Markdown to WeChat', input: 'Markdown with headings, lists, quotes, tables, or code', output: 'rich text ready to paste into the WeChat editor', workflow: 'Choose a theme, check the phone preview, and copy into the official editor.', detail: 'The copy action includes HTML and plain text, which suits publishing from Obsidian, VS Code, or another Markdown editor.', limit: 'The WeChat editor applies its own limits to remote images, complex CSS, dynamic components, and some code styles.', faq: 'The copy button writes rich text and a plain-text fallback, so the result can be pasted and adjusted in the WeChat editor.', related: [{ label: 'Markdown to Xiaohongshu', path: '/markdown-to-xiaohongshu' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    ja: { name: 'MarkdownからWeChat記事へ', input: '見出し、リスト、引用、表、コードを含むMarkdown', output: 'WeChatエディターに貼り付けられるリッチテキスト', workflow: 'テーマを選び、スマートフォン表示を確認して公式エディターへコピーします。', detail: 'HTMLとプレーンテキストを同時にコピーでき、ObsidianやVS Codeからの記事公開に使えます。', limit: 'WeChatエディター側で外部画像、複雑なCSS、動的要素、コード表示に制限があります。', faq: 'コピー操作はリッチテキストとプレーンテキストを用意するため、WeChatエディターで貼り付け後に調整できます。', related: [{ label: 'MarkdownからXiaohongshuへ', path: '/markdown-to-xiaohongshu' }, { label: 'Markdownビューア', path: '/markdown-viewer' }] },
    es: { name: 'Markdown a WeChat', input: 'Markdown con títulos, listas, citas, tablas o código', output: 'texto enriquecido listo para pegar en el editor de WeChat', workflow: 'Elige un tema, revisa la vista móvil y copia al editor oficial.', detail: 'La copia incluye HTML y texto plano, útil para publicar desde Obsidian, VS Code u otro editor Markdown.', limit: 'El editor de WeChat aplica sus propios límites a imágenes remotas, CSS complejo, componentes dinámicos y algunos estilos de código.', faq: 'El botón de copia escribe texto enriquecido y una alternativa de texto plano para pegar y ajustar el artículo.', related: [{ label: 'Markdown a Xiaohongshu', path: '/markdown-to-xiaohongshu' }, { label: 'Visor Markdown', path: '/markdown-viewer' }] },
    de: { name: 'Markdown zu WeChat', input: 'Markdown mit Überschriften, Listen, Zitaten, Tabellen oder Code', output: 'Rich Text zum Einfügen in den WeChat-Editor', workflow: 'Design wählen, mobile Vorschau prüfen und in den offiziellen Editor kopieren.', detail: 'Die Kopie enthält HTML und reinen Text und eignet sich für Veröffentlichungen aus Obsidian, VS Code oder anderen Markdown-Editoren.', limit: 'Der WeChat-Editor begrenzt Remote-Bilder, komplexes CSS, dynamische Komponenten und einige Code-Styles selbst.', faq: 'Die Kopierfunktion schreibt Rich Text und eine Textalternative, die im WeChat-Editor eingefügt und angepasst werden kann.', related: [{ label: 'Markdown zu Xiaohongshu', path: '/markdown-to-xiaohongshu' }, { label: 'Markdown-Viewer', path: '/markdown-viewer' }] },
  },
  'markdown-to-xiaohongshu': {
    zh: { name: 'Markdown转小红书', input: '用标题或分隔线组织的Markdown文章', output: '按卡片分页的浏览器打印结果或PDF', workflow: '用##或---分页，选择主题、比例和字体，再打开打印窗口保存卡片。', detail: '适合把学习笔记、教程、清单和文章拆成3:4、3:5、4:5或1:1图片卡片。', limit: '卡片内容过长会影响可读性，远程图片可能受防盗链或浏览器权限影响。', faq: '##标题会创建新卡片，---会手动分页；点击打印/保存卡片后，可以选择保存为PDF。', related: [{ label: 'Markdown转微信公众号', path: '/markdown-to-wechat' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    en: { name: 'Markdown to Xiaohongshu', input: 'Markdown organized with headings or separators', output: 'print-ready cards or a PDF from the browser print dialog', workflow: 'Use ## or ---, choose a theme, ratio, and font, then open print and save the cards.', detail: 'Useful for turning notes, tutorials, checklists, and articles into 3:4, 3:5, 4:5, or 1:1 cards.', limit: 'Very long card content can reduce readability, and remote images may be limited by hotlink protection or browser permissions.', faq: 'A ## heading starts a new card and --- creates a manual break. Click Print/save cards, then choose Save as PDF if needed.', related: [{ label: 'Markdown to WeChat', path: '/markdown-to-wechat' }, { label: 'Markdown Viewer', path: '/markdown-viewer' }] },
    ja: { name: 'MarkdownからXiaohongshuへ', input: '見出しまたは区切り線で整理したMarkdown', output: 'ブラウザの印刷画面から保存するカードまたはPDF', workflow: '##または---で分割し、テーマ、比率、フォントを選んで印刷画面から保存します。', detail: '学習ノート、チュートリアル、チェックリスト、記事を3:4、3:5、4:5、1:1のカードにできます。', limit: 'カードの長文は読みやすさを下げる場合があり、外部画像は防止設定やブラウザ権限の影響を受けます。', faq: '##見出しで新しいカードを作り、---で手動分割します。印刷/保存ボタンからPDFを保存できます。', related: [{ label: 'MarkdownからWeChat記事へ', path: '/markdown-to-wechat' }, { label: 'Markdownビューア', path: '/markdown-viewer' }] },
    es: { name: 'Markdown a Xiaohongshu', input: 'Un artículo Markdown organizado con títulos o separadores', output: 'tarjetas listas para imprimir o un PDF desde el diálogo de impresión', workflow: 'Usa ## o ---, elige tema, proporción y fuente y abre la impresión para guardar las tarjetas.', detail: 'Convierte notas, tutoriales, listas y artículos en tarjetas con proporciones 3:4, 3:5, 4:5 o 1:1.', limit: 'El contenido demasiado largo reduce la legibilidad y las imágenes remotas pueden depender de permisos o protección anti-hotlink.', faq: 'Un título ## inicia una tarjeta y --- crea un salto manual. Pulsa imprimir/guardar y elige Guardar como PDF si lo necesitas.', related: [{ label: 'Markdown a WeChat', path: '/markdown-to-wechat' }, { label: 'Visor Markdown', path: '/markdown-viewer' }] },
    de: { name: 'Markdown zu Xiaohongshu', input: 'Markdown mit Überschriften oder Trennlinien', output: 'druckfertige Karten oder eine PDF-Datei aus dem Browser-Druckdialog', workflow: '## oder --- verwenden, Design, Verhältnis und Schrift wählen und die Karten über den Druckdialog speichern.', detail: 'Notizen, Tutorials, Checklisten und Artikel in Karten mit 3:4, 3:5, 4:5 oder 1:1 umwandeln.', limit: 'Sehr lange Karten werden schlechter lesbar; Remote-Bilder können durch Hotlink-Schutz oder Browserrechte begrenzt sein.', faq: 'Eine ##-Überschrift beginnt eine neue Karte und --- setzt einen manuellen Umbruch. Über Drucken/Speichern kann eine PDF gespeichert werden.', related: [{ label: 'Markdown zu WeChat', path: '/markdown-to-wechat' }, { label: 'Markdown-Viewer', path: '/markdown-viewer' }] },
  },
  'merge-pptx': {
    zh: { name: 'PPTX合并', input: '至少两个.pptx演示文稿', output: '按文件顺序排列的合并PPTX', workflow: '上传演示文稿，调整顺序，生成后检查幻灯片数量和媒体关系。', detail: '适合合并课程、会议、销售和项目汇报演示文稿，文件在浏览器中处理。', limit: '动画、字体、主题、嵌入对象和复杂媒体关系可能需要在PowerPoint中复核。', faq: '页面会按文件列表顺序拼接幻灯片，并尽量保留图片、布局和媒体关系。', related: [{ label: 'PPT转Markdown', path: '/ppt-to-markdown' }, { label: '文档合并工具', path: '/merge-documents' }] },
    en: { name: 'Merge PPTX', input: 'at least two .pptx presentations', output: 'one PPTX in the selected file order', workflow: 'Upload presentations, arrange their order, and review slide count and media relationships after creation.', detail: 'Useful for combining course, meeting, sales, and project decks while processing files in the browser.', limit: 'Animations, fonts, themes, embedded objects, and complex media relationships may need review in PowerPoint.', faq: 'Slides are appended in the file list order, while images, layouts, and media relationships are preserved where possible.', related: [{ label: 'PPT to Markdown', path: '/ppt-to-markdown' }, { label: 'Merge document tools', path: '/merge-documents' }] },
    ja: { name: 'PPTX結合', input: '2つ以上の.pptxプレゼンテーション', output: '選択順に並んだ1つのPPTX', workflow: 'プレゼンを追加して順番を調整し、生成後にスライド数とメディアを確認します。', detail: '授業、会議、営業、プロジェクト資料を結合でき、ファイルはブラウザ内で処理します。', limit: 'アニメーション、フォント、テーマ、埋め込み要素、複雑なメディア関係はPowerPointで確認が必要です。', faq: 'ファイル一覧の順番でスライドを追加し、画像、レイアウト、メディア関係を可能な範囲で保持します。', related: [{ label: 'PPTからMarkdown', path: '/ppt-to-markdown' }, { label: '文書結合ツール', path: '/merge-documents' }] },
    es: { name: 'Unir PPTX', input: 'al menos dos presentaciones .pptx', output: 'un PPTX en el orden elegido', workflow: 'Sube las presentaciones, ordénalas y revisa las diapositivas y los medios tras crear el archivo.', detail: 'Sirve para combinar presentaciones de cursos, reuniones, ventas y proyectos en el navegador.', limit: 'Las animaciones, fuentes, temas, objetos incrustados y relaciones multimedia complejas pueden necesitar revisión en PowerPoint.', faq: 'Las diapositivas se añaden según el orden de archivos y se conservan imágenes, diseños y relaciones cuando es posible.', related: [{ label: 'PPT a Markdown', path: '/ppt-to-markdown' }, { label: 'Herramientas para unir documentos', path: '/merge-documents' }] },
    de: { name: 'PPTX zusammenführen', input: 'mindestens zwei .pptx-Präsentationen', output: 'eine PPTX in der gewählten Reihenfolge', workflow: 'Präsentationen laden, Reihenfolge festlegen und Folienzahl sowie Medien prüfen.', detail: 'Geeignet zum Verbinden von Kurs-, Meeting-, Vertriebs- und Projektpräsentationen im Browser.', limit: 'Animationen, Schriften, Designs, eingebettete Objekte und komplexe Medienbeziehungen müssen eventuell in PowerPoint geprüft werden.', faq: 'Folien werden in der Dateireihenfolge angehängt; Bilder, Layouts und Medienbeziehungen bleiben möglichst erhalten.', related: [{ label: 'PPT zu Markdown', path: '/ppt-to-markdown' }, { label: 'Dokumente zusammenführen', path: '/merge-documents' }] },
  },
  'merge-excel': {
    zh: { name: 'Excel合并', input: '至少两个.xlsx或.xlsm工作簿', output: '包含多个工作表的合并Excel工作簿', workflow: '选择工作表模式或追加模式，生成后检查表头和行数。', detail: '工作表模式按文件创建独立工作表，追加模式把表格数据接到同一张表中。', limit: '公式、宏、图表、透视表、外部连接和复杂格式可能需要在Excel中复核。', faq: '可以选择每个文件一个工作表，或把兼容的数据追加到同一张工作表。', related: [{ label: 'Excel转Markdown', path: '/excel-to-markdown' }, { label: '文档合并工具', path: '/merge-documents' }] },
    en: { name: 'Merge Excel', input: 'at least two .xlsx or .xlsm workbooks', output: 'one Excel workbook with multiple sheets', workflow: 'Choose sheet or append mode, then review headers and row counts after creation.', detail: 'Sheet mode creates one sheet per file, while append mode adds compatible table rows to one sheet.', limit: 'Formulas, macros, charts, pivot tables, external connections, and complex formatting may need review in Excel.', faq: 'Choose one sheet per file, or append compatible tabular data into a single worksheet.', related: [{ label: 'Excel to Markdown', path: '/excel-to-markdown' }, { label: 'Merge document tools', path: '/merge-documents' }] },
    ja: { name: 'Excel結合', input: '2つ以上の.xlsxまたは.xlsmワークブック', output: '複数シートを含む1つのExcelブック', workflow: 'シートモードまたは追加モードを選び、生成後に見出しと行数を確認します。', detail: 'シートモードはファイルごとにシートを作り、追加モードは互換性のある表データを1枚に追加します。', limit: '数式、マクロ、グラフ、ピボット、外部接続、複雑な書式はExcelで確認が必要です。', faq: 'ファイルごとにシートを作るか、互換性のある表データを1枚のシートへ追加できます。', related: [{ label: 'ExcelからMarkdown', path: '/excel-to-markdown' }, { label: '文書結合ツール', path: '/merge-documents' }] },
    es: { name: 'Unir Excel', input: 'al menos dos libros .xlsx o .xlsm', output: 'un libro Excel con varias hojas', workflow: 'Elige modo de hojas o añadido y revisa encabezados y filas tras crear el archivo.', detail: 'El modo de hojas crea una hoja por archivo y el modo de añadido incorpora filas compatibles en una sola hoja.', limit: 'Las fórmulas, macros, gráficos, tablas dinámicas, conexiones externas y formatos complejos pueden necesitar revisión en Excel.', faq: 'Puedes crear una hoja por archivo o añadir datos tabulares compatibles a una sola hoja.', related: [{ label: 'Excel a Markdown', path: '/excel-to-markdown' }, { label: 'Herramientas para unir documentos', path: '/merge-documents' }] },
    de: { name: 'Excel zusammenführen', input: 'mindestens zwei .xlsx- oder .xlsm-Arbeitsmappen', output: 'eine Excel-Arbeitsmappe mit mehreren Blättern', workflow: 'Blatt- oder Anhängemodus wählen und danach Überschriften sowie Zeilen prüfen.', detail: 'Im Blattmodus entsteht ein Blatt pro Datei; im Anhängemodus werden kompatible Tabellenzeilen in ein Blatt übernommen.', limit: 'Formeln, Makros, Diagramme, Pivot-Tabellen, externe Verbindungen und komplexe Formatierungen müssen eventuell in Excel geprüft werden.', faq: 'Eine Arbeitsmappe pro Datei oder kompatible Tabellendaten in einem gemeinsamen Blatt nutzen.', related: [{ label: 'Excel zu Markdown', path: '/excel-to-markdown' }, { label: 'Dokumente zusammenführen', path: '/merge-documents' }] },
  },
};

const common = {
  zh: { use: '怎么用', prepare: '准备输入', review: '检查结果', export: '下载或复制', example: '输入和输出示例', input: '输入', output: '输出', support: '支持格式和适用场景', limits: '限制条件', privacyTitle: '隐私说明', faq: '常见问题', related: '相关工具', privacy: '文件只在当前浏览器中读取和生成，不上传到Herdown服务器。刷新或关闭页面后不会作为托管文件长期保存。', local: '内容在浏览器本地处理。' },
  en: { use: 'How to use', prepare: 'Prepare the input', review: 'Review the result', export: 'Download or copy', example: 'Input and output example', input: 'Input', output: 'Output', support: 'Supported format and use cases', limits: 'Limitations', privacyTitle: 'Privacy', faq: 'FAQ', related: 'Related tools', privacy: 'Files are read and generated in this browser. They are not uploaded to Herdown or kept as hosted files after the page is closed.', local: 'Processing runs in the browser.' },
  ja: { use: '使い方', prepare: '入力を準備', review: '結果を確認', export: '保存またはコピー', example: '入力と出力の例', input: '入力', output: '出力', support: '対応形式と用途', limits: '制限', privacyTitle: 'プライバシー', faq: 'よくある質問', related: '関連ツール', privacy: 'ファイルはこのブラウザで読み取りと生成を行い、Herdownへアップロードしません。ページを閉じた後にホスト保存もしません。', local: '処理はブラウザ内で行います。' },
  es: { use: 'Cómo usarlo', prepare: 'Preparar la entrada', review: 'Revisar el resultado', export: 'Descargar o copiar', example: 'Ejemplo de entrada y salida', input: 'Entrada', output: 'Salida', support: 'Formato y usos', limits: 'Limitaciones', privacyTitle: 'Privacidad', faq: 'Preguntas frecuentes', related: 'Herramientas relacionadas', privacy: 'Los archivos se leen y generan en este navegador. No se suben a Herdown ni se guardan como archivos alojados después de cerrar la página.', local: 'El procesamiento se realiza en el navegador.' },
  de: { use: 'Anleitung', prepare: 'Eingabe vorbereiten', review: 'Ergebnis prüfen', export: 'Laden oder kopieren', example: 'Beispiel für Eingabe und Ausgabe', input: 'Eingabe', output: 'Ausgabe', support: 'Format und Einsatz', limits: 'Einschränkungen', privacyTitle: 'Datenschutz', faq: 'FAQ', related: 'Verwandte Werkzeuge', privacy: 'Dateien werden in diesem Browser gelesen und erzeugt. Sie werden nicht zu Herdown hochgeladen oder nach dem Schließen als gehostete Dateien gespeichert.', local: 'Die Verarbeitung findet im Browser statt.' },
} satisfies Record<Language, Record<string, string>>;

export const buildAdditionalToolSeoCopy = (slug: AddedToolSeoSlug, language: Language): ToolSeoCopy => {
  const profile = profiles[slug][language];
  const labels = common[language];
  const useTitle = language === 'zh' ? `${profile.name}${labels.use}` : `${profile.name} — ${labels.use}`;
  const faqTitle = language === 'zh' ? `${profile.name}${labels.faq}` : `${profile.name} ${labels.faq}`;
  const sentenceSeparator = language === 'zh' || language === 'ja' ? '。' : '. ';
  const questionSeparator = language === 'zh' || language === 'ja' ? '？' : '?';
  const labelSeparator = language === 'zh' || language === 'ja' ? '：' : ': ';
  return {
    useTitle,
    steps: [
      { title: labels.prepare, text: `${profile.input}${sentenceSeparator}${labels.local}` },
      { title: labels.review, text: profile.workflow },
      { title: labels.export, text: `${profile.output}${sentenceSeparator}${profile.faq}` },
    ],
    exampleTitle: labels.example,
    inputLabel: labels.input,
    inputExample: profile.input,
    outputLabel: labels.output,
    outputExample: profile.output,
    supportTitle: labels.support,
    support: [profile.input, profile.output, profile.detail],
    limitsTitle: labels.limits,
    limits: [profile.limit, labels.local],
    privacyTitle: labels.privacyTitle,
    privacy: labels.privacy,
    faqTitle,
    faqs: [
      { question: `${labels.input}${labelSeparator}${profile.input}${questionSeparator}`, answer: profile.detail },
      { question: `${labels.output}${labelSeparator}${profile.output}${questionSeparator}`, answer: profile.faq },
      { question: `${labels.limits}${questionSeparator}`, answer: profile.limit },
    ],
    relatedTitle: labels.related,
    related: profile.related,
  };
};
