import type { Language } from './i18n';
import { buildAdditionalToolSeoCopy } from './AdditionalToolSeoContent';
import type { AddedToolSeoSlug } from './AdditionalToolSeoContent';

export type ToolSeoSlug = 'merge-pdf' | 'merge-docx' | 'sitemap-generator' | 'sitemap-checker' | 'markdown-viewer' | 'pdf-to-markdown' | 'markdown-to-html' | 'markdown-to-pdf' | 'markdown-to-word' | 'markdown-to-csv' | 'markdown-to-wechat' | 'markdown-to-xiaohongshu' | 'merge-pptx' | 'merge-excel';

export type ToolSeoCopy = {
  useTitle: string;
  steps: Array<{ title: string; text: string }>;
  exampleTitle: string;
  inputLabel: string;
  inputExample: string;
  outputLabel: string;
  outputExample: string;
  supportTitle: string;
  support: string[];
  limitsTitle: string;
  limits: string[];
  privacyTitle: string;
  privacy: string;
  faqTitle: string;
  faqs: Array<{ question: string; answer: string }>;
  relatedTitle: string;
  related: Array<{ label: string; path: string }>;
};

const copy: Partial<Record<ToolSeoSlug, Record<Language, ToolSeoCopy>>> = {
  'merge-pdf': {
    zh: {
      useTitle: 'PDF合并怎么用',
      steps: [
        { title: '选择文件', text: '添加至少2个PDF，工具会在浏览器中读取文件名和页面结构。' },
        { title: '确认顺序', text: '用上移、下移或移除按钮调整文件顺序，最终页码会按这个顺序排列。' },
        { title: '合并下载', text: '点击合并PDF，生成文件通过结构校验后，再下载合并结果。' },
      ],
      exampleTitle: '输入和输出示例',
      inputLabel: '输入文件',
      inputExample: '报价单.pdf\n合同.pdf\n附件.pdf',
      outputLabel: '输出文件',
      outputExample: 'herdown-merged.pdf\n第1部分：报价单\n第2部分：合同\n第3部分：附件',
      supportTitle: '支持格式和适用场景',
      support: ['输入格式：.pdf', '输出格式：单个.pdf文件', '适合合并报告、合同、发票、资料附件和打印材料', '页面、文字、图片和矢量内容会按文件顺序写入结果'],
      limitsTitle: '限制条件',
      limits: ['加密、需要密码或已经损坏的PDF可能无法读取', 'PDF书签、表单填写状态、数字签名和部分交互内容不一定能保留', '合并后用于正式签署或提交前，应在PDF阅读器中检查页码、字体和签名状态'],
      privacyTitle: '隐私说明',
      privacy: 'PDF只在当前浏览器中读取和生成，不上传到Herdown服务器。刷新页面或关闭标签页后，页面状态不会作为文档长期保存。',
      faqTitle: 'PDF合并FAQ',
      faqs: [
        { question: '至少需要几个PDF？', answer: '至少2个。单个PDF不需要合并，直接下载原文件即可。' },
        { question: '文件顺序可以调整吗？', answer: '可以。合并前使用每个文件旁边的上移和下移按钮，结果会按当前列表顺序生成。' },
        { question: '为什么合并按钮不可用？', answer: '通常是因为还没有选择2个有效PDF，或文件扩展名不是.pdf。' },
      ],
      relatedTitle: '相关工具',
      related: [{ label: 'PDF转Markdown', path: '/pdf-to-markdown' }, { label: 'Sitemap检查器', path: '/sitemap-checker' }],
    },
    en: {
      useTitle: 'How to merge PDF files',
      steps: [
        { title: 'Choose files', text: 'Add at least two PDFs. The browser reads their file names and page structure locally.' },
        { title: 'Check the order', text: 'Use the move and remove controls to set the page order before merging.' },
        { title: 'Merge and download', text: 'Select Merge PDF. The generated file is checked before the download action is enabled.' },
      ],
      exampleTitle: 'Input and output example', inputLabel: 'Input files', inputExample: 'quote.pdf\ncontract.pdf\nappendix.pdf', outputLabel: 'Output file', outputExample: 'herdown-merged.pdf\nPart 1: quote\nPart 2: contract\nPart 3: appendix',
      supportTitle: 'Supported format and use cases', support: ['Input: .pdf', 'Output: one .pdf file', 'Useful for reports, contracts, invoices, attachments, and print-ready material', 'Pages, text, images, and vector content are written in the selected order'],
      limitsTitle: 'Limitations', limits: ['Encrypted, password-protected, or damaged PDFs may not open', 'Bookmarks, form state, digital signatures, and some interactive content may not survive', 'Review page numbers, fonts, and signature status in a PDF reader before formal submission'],
      privacyTitle: 'Privacy', privacy: 'PDF files are read and generated in this browser. They are not uploaded to Herdown, and the document is not stored as a hosted file after the page is closed.',
      faqTitle: 'Merge PDF FAQ', faqs: [{ question: 'How many PDFs are required?', answer: 'At least two. A single PDF does not need merging.' }, { question: 'Can I change the order?', answer: 'Yes. Move files up or down before merging. The list order becomes the output page order.' }, { question: 'Why is the merge button disabled?', answer: 'Choose at least two valid files with the .pdf extension.' }],
      relatedTitle: 'Related tools', related: [{ label: 'PDF to Markdown', path: '/pdf-to-markdown' }, { label: 'Sitemap checker', path: '/sitemap-checker' }],
    },
    ja: {
      useTitle: 'PDF結合の使い方',
      steps: [{ title: 'ファイルを選択', text: '2つ以上のPDFを追加します。ファイル名とページ構造はブラウザ内で読み取ります。' }, { title: '順番を確認', text: '上へ、下へ、削除の操作で結合後のページ順を調整します。' }, { title: '結合して保存', text: 'PDFを結合を押すと、生成ファイルを確認してからダウンロードできます。' }],
      exampleTitle: '入力と出力の例', inputLabel: '入力ファイル', inputExample: '見積書.pdf\n契約書.pdf\n添付資料.pdf', outputLabel: '出力ファイル', outputExample: 'herdown-merged.pdf\n第1部：見積書\n第2部：契約書\n第3部：添付資料',
      supportTitle: '対応形式と用途', support: ['入力形式：.pdf', '出力形式：1つの.pdfファイル', 'レポート、契約書、請求書、添付資料に利用できます', 'ページ、テキスト、画像、ベクター情報を選択順に結合します'],
      limitsTitle: '制限', limits: ['暗号化、パスワード保護、破損したPDFは開けない場合があります', 'しおり、フォームの状態、電子署名、対話要素は保持されない場合があります', '提出前にPDFリーダーでページ、フォント、署名状態を確認してください'],
      privacyTitle: 'プライバシー', privacy: 'PDFはこのブラウザ内で読み取りと生成を行い、Herdownへアップロードしません。ページを閉じた後に文書をホスト保存することもありません。',
      faqTitle: 'PDF結合FAQ', faqs: [{ question: '何個のPDFが必要ですか？', answer: '2個以上です。1個のPDFはそのまま利用できます。' }, { question: '順番を変えられますか？', answer: 'はい。結合前に上へ、下へを使って順番を変更できます。' }, { question: '結合ボタンが押せません。', answer: '有効なPDFを2個以上選択してください。' }],
      relatedTitle: '関連ツール', related: [{ label: 'PDFからMarkdown', path: '/pdf-to-markdown' }, { label: 'Sitemapチェッカー', path: '/sitemap-checker' }],
    },
    es: {
      useTitle: 'Cómo unir archivos PDF',
      steps: [{ title: 'Elegir archivos', text: 'Añade al menos dos PDF. El navegador lee sus nombres y páginas localmente.' }, { title: 'Revisar el orden', text: 'Usa los controles para subir, bajar o quitar archivos antes de unirlos.' }, { title: 'Unir y descargar', text: 'Pulsa Unir PDF. El archivo generado se comprueba antes de habilitar la descarga.' }],
      exampleTitle: 'Ejemplo de entrada y salida', inputLabel: 'Archivos de entrada', inputExample: 'presupuesto.pdf\ncontrato.pdf\nanexo.pdf', outputLabel: 'Archivo de salida', outputExample: 'herdown-merged.pdf\nParte 1: presupuesto\nParte 2: contrato\nParte 3: anexo',
      supportTitle: 'Formato y usos', support: ['Entrada: .pdf', 'Salida: un archivo .pdf', 'Útil para informes, contratos, facturas, anexos y material de impresión', 'Las páginas, el texto, las imágenes y los vectores siguen el orden elegido'],
      limitsTitle: 'Limitaciones', limits: ['Los PDF cifrados, protegidos con contraseña o dañados pueden no abrirse', 'Los marcadores, formularios, firmas digitales y elementos interactivos pueden no conservarse', 'Revisa páginas, fuentes y firmas en un lector PDF antes de entregar el archivo'],
      privacyTitle: 'Privacidad', privacy: 'Los PDF se leen y generan en este navegador. No se suben a Herdown ni se guardan como archivos alojados después de cerrar la página.',
      faqTitle: 'Preguntas sobre unir PDF', faqs: [{ question: '¿Cuántos PDF necesito?', answer: 'Al menos dos. Un PDF individual no necesita unión.' }, { question: '¿Puedo cambiar el orden?', answer: 'Sí. Sube o baja los archivos antes de unirlos.' }, { question: '¿Por qué está desactivado el botón?', answer: 'Selecciona al menos dos archivos válidos con extensión .pdf.' }],
      relatedTitle: 'Herramientas relacionadas', related: [{ label: 'PDF a Markdown', path: '/pdf-to-markdown' }, { label: 'Comprobador de Sitemap', path: '/sitemap-checker' }],
    },
    de: {
      useTitle: 'PDF-Dateien zusammenführen',
      steps: [{ title: 'Dateien auswählen', text: 'Füge mindestens zwei PDFs hinzu. Namen und Seitenstruktur werden lokal im Browser gelesen.' }, { title: 'Reihenfolge prüfen', text: 'Mit den Schaltflächen kannst du Dateien verschieben oder entfernen.' }, { title: 'Zusammenführen und laden', text: 'Klicke auf PDF zusammenführen. Die Datei wird vor dem Download geprüft.' }],
      exampleTitle: 'Beispiel für Eingabe und Ausgabe', inputLabel: 'Eingabedateien', inputExample: 'angebot.pdf\nvertrag.pdf\nanlage.pdf', outputLabel: 'Ausgabedatei', outputExample: 'herdown-merged.pdf\nTeil 1: Angebot\nTeil 2: Vertrag\nTeil 3: Anlage',
      supportTitle: 'Format und Einsatz', support: ['Eingabe: .pdf', 'Ausgabe: eine .pdf-Datei', 'Geeignet für Berichte, Verträge, Rechnungen, Anlagen und Druckmaterial', 'Seiten, Text, Bilder und Vektorinhalte folgen der gewählten Reihenfolge'],
      limitsTitle: 'Einschränkungen', limits: ['Verschlüsselte, passwortgeschützte oder beschädigte PDFs lassen sich möglicherweise nicht öffnen', 'Lesezeichen, Formularstatus, digitale Signaturen und interaktive Inhalte werden eventuell nicht erhalten', 'Prüfe Seiten, Schriften und Signaturen vor einer offiziellen Abgabe in einem PDF-Reader'],
      privacyTitle: 'Datenschutz', privacy: 'PDFs werden in diesem Browser gelesen und erzeugt. Sie werden nicht zu Herdown hochgeladen und nach dem Schließen der Seite nicht als Datei gehostet.',
      faqTitle: 'FAQ zum Zusammenführen von PDFs', faqs: [{ question: 'Wie viele PDFs brauche ich?', answer: 'Mindestens zwei. Eine einzelne PDF muss nicht zusammengeführt werden.' }, { question: 'Kann ich die Reihenfolge ändern?', answer: 'Ja. Verschiebe die Dateien vor dem Zusammenführen nach oben oder unten.' }, { question: 'Warum ist die Schaltfläche deaktiviert?', answer: 'Wähle mindestens zwei gültige Dateien mit der Endung .pdf aus.' }],
      relatedTitle: 'Verwandte Werkzeuge', related: [{ label: 'PDF zu Markdown', path: '/pdf-to-markdown' }, { label: 'Sitemap-Prüfer', path: '/sitemap-checker' }],
    },
  },
  'merge-docx': {
    zh: {
      useTitle: 'DOCX合并怎么用', steps: [{ title: '添加Word文档', text: '选择至少2个.docx文件，工具会在当前浏览器中读取文档包。' }, { title: '排列章节顺序', text: '文件列表顺序会成为合并文档的章节顺序，必要时可以上移、下移或移除。' }, { title: '生成DOCX', text: '点击合并DOCX，完成结构校验后下载可继续编辑的Word文档。' }], exampleTitle: '输入和输出示例', inputLabel: '输入文件', inputExample: '项目概述.docx\n需求说明.docx\n附录.docx', outputLabel: '输出文件', outputExample: 'herdown-merged.docx\n项目概述\n需求说明\n附录', supportTitle: '支持格式和适用场景', support: ['输入格式：.docx', '输出格式：可继续编辑的.docx', '适合合并报告章节、会议材料、合同附件和交付文档', '正文样式、表格、图片、项目符号和编号会尽量保留'], limitsTitle: '限制条件', limits: ['批注、修订记录、宏、嵌入对象和复杂编号样式可能需要在Word中复核', '不同文档的主题、页眉页脚和样式同名时，结果可能以首个文档的定义为准', '如果文档包含敏感信息，下载后仍应按你的文件管理规则保存'], privacyTitle: '隐私说明', privacy: 'DOCX文件只在当前浏览器中读取和生成，不上传到Herdown服务器。合并结果通过浏览器下载到你的设备。', faqTitle: 'DOCX合并FAQ', faqs: [{ question: '会保留原来的格式吗？', answer: '工具会尽量保留正文样式、表格、图片、列表和编号，但复杂Word特性需要在Word中复核。' }, { question: '合并后文档之间会粘在一起吗？', answer: '工具会在文档之间插入分页，便于区分原始文件。' }, { question: '可以合并.doc文件吗？', answer: '当前独立页面处理.docx，不处理旧版二进制.doc文件。' }], relatedTitle: '相关工具', related: [{ label: 'DOCX转Markdown', path: '/word-to-markdown' }, { label: 'PDF合并', path: '/merge-pdf' }],
    },
    en: {
      useTitle: 'How to merge DOCX files', steps: [{ title: 'Add Word documents', text: 'Choose at least two .docx files. The browser reads the document packages locally.' }, { title: 'Arrange the sections', text: 'The file list becomes the section order. Move or remove files before merging.' }, { title: 'Create the DOCX', text: 'Select Merge DOCX and download the editable Word document after validation.' }], exampleTitle: 'Input and output example', inputLabel: 'Input files', inputExample: 'overview.docx\nrequirements.docx\nappendix.docx', outputLabel: 'Output file', outputExample: 'herdown-merged.docx\nOverview\nRequirements\nAppendix', supportTitle: 'Supported format and use cases', support: ['Input: .docx', 'Output: editable .docx', 'Useful for reports, meeting material, contract appendices, and delivery documents', 'Body styles, tables, images, bullets, and numbering are preserved when possible'], limitsTitle: 'Limitations', limits: ['Comments, tracked changes, macros, embedded objects, and complex numbering may need a Word review', 'When documents define the same theme or style differently, the first document may provide the definition', 'Handle downloaded files under your normal document security rules'], privacyTitle: 'Privacy', privacy: 'DOCX files are read and generated in this browser. They are not uploaded to Herdown, and the merged result is downloaded to your device.', faqTitle: 'Merge DOCX FAQ', faqs: [{ question: 'Are the original styles preserved?', answer: 'The tool attempts to preserve body styles, tables, images, lists, and numbering. Complex Word features should be reviewed.' }, { question: 'Are documents separated?', answer: 'A page break is inserted between source documents.' }, { question: 'Can I merge old .doc files?', answer: 'This page handles .docx files, not the older binary .doc format.' }], relatedTitle: 'Related tools', related: [{ label: 'DOCX to Markdown', path: '/word-to-markdown' }, { label: 'Merge PDF', path: '/merge-pdf' }],
    },
    ja: {
      useTitle: 'DOCX結合の使い方', steps: [{ title: 'Word文書を追加', text: '2つ以上の.docxを選択します。文書パッケージはブラウザ内で読み取ります。' }, { title: '章の順番を調整', text: 'ファイルの順番が結合後の章の順番になります。上へ、下へ、削除を使えます。' }, { title: 'DOCXを生成', text: 'DOCXを結合を押し、検証後に編集可能なWord文書を保存します。' }], exampleTitle: '入力と出力の例', inputLabel: '入力ファイル', inputExample: '概要.docx\n要件.docx\n付録.docx', outputLabel: '出力ファイル', outputExample: 'herdown-merged.docx\n概要\n要件\n付録', supportTitle: '対応形式と用途', support: ['入力形式：.docx', '出力形式：編集可能な.docx', 'レポート、会議資料、契約書の付録、納品文書に利用できます', '本文の書式、表、画像、箇条書き、番号を可能な限り保持します'], limitsTitle: '制限', limits: ['コメント、変更履歴、マクロ、埋め込みオブジェクト、複雑な番号はWordで確認してください', 'テーマや同名スタイルが異なる場合、最初の文書の定義が使われることがあります', 'ダウンロード後は通常の文書管理ルールで扱ってください'], privacyTitle: 'プライバシー', privacy: 'DOCXはこのブラウザ内で読み取りと生成を行い、Herdownへアップロードしません。結合結果は端末へダウンロードします。', faqTitle: 'DOCX結合FAQ', faqs: [{ question: '書式は保持されますか？', answer: '本文、表、画像、リスト、番号を可能な限り保持しますが、複雑な機能はWordで確認してください。' }, { question: '文書は区切られますか？', answer: '文書の間に改ページを入れます。' }, { question: '古い.docも対応しますか？', answer: 'このページは.docxに対応し、旧形式の.docは扱いません。' }], relatedTitle: '関連ツール', related: [{ label: 'DOCXからMarkdown', path: '/word-to-markdown' }, { label: 'PDF結合', path: '/merge-pdf' }],
    },
    es: {
      useTitle: 'Cómo unir archivos DOCX', steps: [{ title: 'Añadir documentos Word', text: 'Elige al menos dos archivos .docx. El navegador lee los paquetes localmente.' }, { title: 'Ordenar las secciones', text: 'El orden de los archivos se convierte en el orden de las secciones.' }, { title: 'Crear el DOCX', text: 'Pulsa Unir DOCX y descarga el documento editable tras la validación.' }], exampleTitle: 'Ejemplo de entrada y salida', inputLabel: 'Archivos de entrada', inputExample: 'resumen.docx\nrequisitos.docx\nanexo.docx', outputLabel: 'Archivo de salida', outputExample: 'herdown-merged.docx\nResumen\nRequisitos\nAnexo', supportTitle: 'Formato y usos', support: ['Entrada: .docx', 'Salida: .docx editable', 'Útil para informes, actas, anexos contractuales y documentos de entrega', 'Se conservan estilos, tablas, imágenes, viñetas y numeración cuando es posible'], limitsTitle: 'Limitaciones', limits: ['Los comentarios, cambios controlados, macros, objetos incrustados y numeraciones complejas requieren revisión en Word', 'Si los documentos definen estilos o temas iguales de forma distinta, puede prevalecer el primer documento', 'Aplica tus reglas habituales de seguridad al guardar el archivo descargado'], privacyTitle: 'Privacidad', privacy: 'Los DOCX se leen y generan en este navegador. No se suben a Herdown y el resultado se descarga en tu equipo.', faqTitle: 'Preguntas sobre unir DOCX', faqs: [{ question: '¿Se conservan los estilos?', answer: 'Se intentan conservar estilos, tablas, imágenes, listas y numeración. Revisa las funciones complejas en Word.' }, { question: '¿Se separan los documentos?', answer: 'Se inserta un salto de página entre documentos.' }, { question: '¿Admite archivos .doc antiguos?', answer: 'Esta página procesa .docx, no el formato binario antiguo .doc.' }], relatedTitle: 'Herramientas relacionadas', related: [{ label: 'DOCX a Markdown', path: '/word-to-markdown' }, { label: 'Unir PDF', path: '/merge-pdf' }],
    },
    de: {
      useTitle: 'DOCX-Dateien zusammenführen', steps: [{ title: 'Word-Dokumente hinzufügen', text: 'Wähle mindestens zwei .docx-Dateien. Die Dokumentpakete werden lokal im Browser gelesen.' }, { title: 'Abschnitte ordnen', text: 'Die Dateireihenfolge wird zur Reihenfolge der Abschnitte.' }, { title: 'DOCX erstellen', text: 'Klicke auf DOCX zusammenführen und lade das bearbeitbare Dokument nach der Prüfung.' }], exampleTitle: 'Beispiel für Eingabe und Ausgabe', inputLabel: 'Eingabedateien', inputExample: 'überblick.docx\nanforderungen.docx\nanhang.docx', outputLabel: 'Ausgabedatei', outputExample: 'herdown-merged.docx\nÜberblick\nAnforderungen\nAnhang', supportTitle: 'Format und Einsatz', support: ['Eingabe: .docx', 'Ausgabe: bearbeitbare .docx', 'Geeignet für Berichte, Sitzungsunterlagen, Vertragsanhänge und Lieferdokumente', 'Textformatierung, Tabellen, Bilder, Aufzählungen und Nummerierung werden möglichst erhalten'], limitsTitle: 'Einschränkungen', limits: ['Kommentare, Änderungsverfolgung, Makros, eingebettete Objekte und komplexe Nummerierungen müssen eventuell in Word geprüft werden', 'Bei unterschiedlichen Definitionen gleicher Stile oder Themen kann das erste Dokument maßgeblich sein', 'Behandle die geladene Datei nach deinen üblichen Sicherheitsregeln'], privacyTitle: 'Datenschutz', privacy: 'DOCX-Dateien werden in diesem Browser gelesen und erzeugt. Sie werden nicht zu Herdown hochgeladen und das Ergebnis wird auf dein Gerät geladen.', faqTitle: 'FAQ zum Zusammenführen von DOCX', faqs: [{ question: 'Bleiben Formatierungen erhalten?', answer: 'Formatierungen, Tabellen, Bilder, Listen und Nummerierungen werden möglichst erhalten. Komplexe Funktionen sollten geprüft werden.' }, { question: 'Werden Dokumente getrennt?', answer: 'Zwischen den Quelldokumenten wird ein Seitenumbruch eingefügt.' }, { question: 'Kann ich alte .doc-Dateien nutzen?', answer: 'Diese Seite verarbeitet .docx, nicht das ältere binäre .doc-Format.' }], relatedTitle: 'Verwandte Werkzeuge', related: [{ label: 'DOCX zu Markdown', path: '/word-to-markdown' }, { label: 'PDF zusammenführen', path: '/merge-pdf' }],
    },
  },
  'sitemap-checker': {
    zh: {
      useTitle: 'Sitemap检查器怎么用', steps: [{ title: '输入网站', text: '输入域名或Sitemap地址，工具会检查robots.txt声明和常见Sitemap路径。' }, { title: '查看检查项', text: '结果会分别展示可访问性、XML根结构、Sitemap数量、URL数量和重复地址。' }, { title: '处理问题', text: '根据每一项的通过、警告或错误状态，修正文件后再重新检查。' }], exampleTitle: '输入和输出示例', inputLabel: '输入', inputExample: 'https://example.com\n或\nhttps://example.com/sitemap.xml', outputLabel: '检查结果', outputExample: '发现：robots.txt\n结构：urlset\n去重URL：128\n重复URL：0\n状态：healthy', supportTitle: '检查范围', support: ['发现robots.txt中的Sitemap声明和常见地址', '识别urlset与sitemapindex，并展开可读取的子Sitemap', '统计去重URL并报告重复地址', '适合上线前、改版后、迁移后和提交搜索引擎前检查'], limitsTitle: '限制条件', limits: ['只检查公开可访问的Sitemap，不检查需要登录的后台文件', '评分用于快速发现问题，不等同于GoogleSearchConsole的收录报告', '网络超时、服务器限流或robots.txt限制可能导致结果不完整'], privacyTitle: '隐私说明', privacy: '检查器只请求你输入的公开网址和相关Sitemap，不读取你电脑上的文件，也不会把站点内容作为长期资料保存。', faqTitle: 'Sitemap检查FAQ', faqs: [{ question: '没有robots.txt还能检查吗？', answer: '可以。工具会继续尝试常见Sitemap路径，并在结果中标记没有发现robots.txt。' }, { question: '评分是不是搜索引擎排名？', answer: '不是。评分只概括本页实际检查到的可访问性、结构和URL问题。' }, { question: '为什么URL数量可能不完整？', answer: '大型Sitemap、子文件过多、网络超时或服务端限制都可能让本次结果被截断。' }], relatedTitle: '相关工具', related: [{ label: 'Sitemap生成器', path: '/sitemap-generator' }, { label: 'SitemapURL提取器', path: '/sitemap-extractor' }],
    },
    en: {
      useTitle: 'How to check a sitemap', steps: [{ title: 'Enter a site', text: 'Enter a domain or sitemap URL. The checker looks at robots.txt declarations and common sitemap paths.' }, { title: 'Review the checks', text: 'The result separates availability, XML root type, sitemap count, URL count, and duplicate URLs.' }, { title: 'Fix and recheck', text: 'Use each pass, warning, or error message to make a targeted fix and run the check again.' }], exampleTitle: 'Input and output example', inputLabel: 'Input', inputExample: 'https://example.com\nor\nhttps://example.com/sitemap.xml', outputLabel: 'Check result', outputExample: 'Discovery: robots.txt found\nStructure: urlset\nUnique URLs: 128\nDuplicates: 0\nStatus: healthy', supportTitle: 'What it checks', support: ['Finds sitemap declarations in robots.txt and common locations', 'Recognizes urlset and sitemapindex roots and follows readable child sitemaps', 'Counts unique URLs and reports duplicates', 'Useful before launch, after a migration, or before submitting to a search engine'], limitsTitle: 'Limitations', limits: ['It checks public sitemaps, not private files behind a login', 'The score is a diagnostic summary, not a Google Search Console indexing report', 'Timeouts, rate limits, and robots.txt rules can make a result incomplete'], privacyTitle: 'Privacy', privacy: 'The checker requests only the public URL and related sitemaps you provide. It does not read local files or keep site content as a hosted document.', faqTitle: 'Sitemap checker FAQ', faqs: [{ question: 'Can I check a site without robots.txt?', answer: 'Yes. The checker continues with common sitemap paths and reports that robots.txt was not found.' }, { question: 'Is the score a search ranking?', answer: 'No. It summarizes the availability, structure, and URL issues observed by this page.' }, { question: 'Why can the URL count be incomplete?', answer: 'Large files, many child sitemaps, timeouts, or server limits can truncate a run.' }], relatedTitle: 'Related tools', related: [{ label: 'Sitemap generator', path: '/sitemap-generator' }, { label: 'Sitemap URL extractor', path: '/sitemap-extractor' }],
    },
    ja: {
      useTitle: 'Sitemapチェッカーの使い方', steps: [{ title: 'サイトを入力', text: 'ドメインまたはSitemapのURLを入力し、robots.txtと一般的な場所を確認します。' }, { title: '項目を確認', text: 'アクセス、XMLのルート、Sitemap数、URL数、重複URLを分けて表示します。' }, { title: '修正して再確認', text: '合格、警告、エラーの内容に対応し、修正後にもう一度確認します。' }], exampleTitle: '入力と出力の例', inputLabel: '入力', inputExample: 'https://example.com\nまたは\nhttps://example.com/sitemap.xml', outputLabel: 'チェック結果', outputExample: '発見：robots.txtあり\n構造：urlset\n重複なしURL：128\n重複：0\n状態：healthy', supportTitle: '確認する内容', support: ['robots.txtの宣言と一般的なSitemapの場所を探します', 'urlsetとsitemapindexを識別し、読める子Sitemapを展開します', '重複を除いたURL数と重複URLを確認します', '公開前、移行後、検索エンジンへの送信前に利用できます'], limitsTitle: '制限', limits: ['ログインが必要な非公開ファイルは確認しません', 'スコアは簡易診断であり、GoogleSearchConsoleの登録レポートではありません', 'タイムアウト、レート制限、robots.txtにより結果が不完全になる場合があります'], privacyTitle: 'プライバシー', privacy: '入力した公開URLと関連Sitemapだけをリクエストします。端末内のファイルを読み取らず、サイト内容を長期保存しません。', faqTitle: 'SitemapチェッカーFAQ', faqs: [{ question: 'robots.txtがなくても確認できますか？', answer: 'はい。一般的なSitemapの場所を続けて確認し、robots.txtがないことを結果に表示します。' }, { question: 'スコアは検索順位ですか？', answer: 'いいえ。このページで確認したアクセス、構造、URLの状態をまとめたものです。' }, { question: 'URL数が不完全なのはなぜですか？', answer: '大きなファイル、子Sitemapの数、タイムアウト、サーバー制限が原因になる場合があります。' }], relatedTitle: '関連ツール', related: [{ label: 'Sitemapジェネレーター', path: '/sitemap-generator' }, { label: 'SitemapURL抽出', path: '/sitemap-extractor' }],
    },
    es: {
      useTitle: 'Cómo comprobar un Sitemap', steps: [{ title: 'Introducir el sitio', text: 'Escribe un dominio o una URL de Sitemap. Se revisan robots.txt y las rutas habituales.' }, { title: 'Revisar las comprobaciones', text: 'El resultado separa acceso, raíz XML, cantidad de Sitemaps, URLs y duplicados.' }, { title: 'Corregir y repetir', text: 'Aplica cada aviso o error y vuelve a ejecutar la comprobación.' }], exampleTitle: 'Ejemplo de entrada y salida', inputLabel: 'Entrada', inputExample: 'https://example.com\no\nhttps://example.com/sitemap.xml', outputLabel: 'Resultado', outputExample: 'Descubrimiento: robots.txt encontrado\nEstructura: urlset\nURLs únicas: 128\nDuplicadas: 0\nEstado: healthy', supportTitle: 'Qué comprueba', support: ['Busca declaraciones en robots.txt y ubicaciones habituales', 'Reconoce urlset y sitemapindex y sigue Sitemaps secundarios accesibles', 'Cuenta URLs únicas e informa de duplicados', 'Sirve antes de publicar, después de migrar o antes de enviar a un buscador'], limitsTitle: 'Limitaciones', limits: ['Comprueba Sitemaps públicos, no archivos privados con inicio de sesión', 'La puntuación es un diagnóstico y no un informe de indexación de GoogleSearchConsole', 'Los tiempos de espera, límites del servidor y robots.txt pueden dejar resultados incompletos'], privacyTitle: 'Privacidad', privacy: 'Solo solicita la URL pública y los Sitemaps relacionados que indiques. No lee archivos locales ni conserva el contenido como documento alojado.', faqTitle: 'Preguntas sobre Sitemap', faqs: [{ question: '¿Puedo comprobar un sitio sin robots.txt?', answer: 'Sí. Continúa con las rutas habituales y muestra que no se encontró robots.txt.' }, { question: '¿La puntuación es una posición en buscadores?', answer: 'No. Resume los problemas de acceso, estructura y URLs observados en esta página.' }, { question: '¿Por qué puede faltar parte de las URLs?', answer: 'Los archivos grandes, muchos Sitemaps secundarios, tiempos de espera o límites del servidor pueden truncar el resultado.' }], relatedTitle: 'Herramientas relacionadas', related: [{ label: 'Generador de Sitemap', path: '/sitemap-generator' }, { label: 'Extractor de URLs de Sitemap', path: '/sitemap-extractor' }],
    },
    de: {
      useTitle: 'Sitemap prüfen', steps: [{ title: 'Website eingeben', text: 'Gib eine Domain oder Sitemap-URL ein. robots.txt und übliche Pfade werden geprüft.' }, { title: 'Prüfungen ansehen', text: 'Das Ergebnis trennt Erreichbarkeit, XML-Wurzel, Sitemap-Anzahl, URLs und Duplikate.' }, { title: 'Korrigieren und erneut prüfen', text: 'Behebe Warnungen oder Fehler gezielt und starte die Prüfung erneut.' }], exampleTitle: 'Beispiel für Eingabe und Ausgabe', inputLabel: 'Eingabe', inputExample: 'https://example.com\noder\nhttps://example.com/sitemap.xml', outputLabel: 'Prüfergebnis', outputExample: 'Fundstelle: robots.txt gefunden\nStruktur: urlset\nEindeutige URLs: 128\nDuplikate: 0\nStatus: healthy', supportTitle: 'Geprüfter Umfang', support: ['Findet Sitemap-Angaben in robots.txt und an üblichen Pfaden', 'Erkennt urlset und sitemapindex und folgt lesbaren Unter-Sitemaps', 'Zählt eindeutige URLs und meldet Duplikate', 'Geeignet vor dem Start, nach einer Migration oder vor der Einreichung bei Suchmaschinen'], limitsTitle: 'Einschränkungen', limits: ['Geprüft werden öffentliche Sitemaps, keine Dateien hinter einem Login', 'Der Score ist eine Diagnose und kein Indexierungsbericht der GoogleSearchConsole', 'Timeouts, Serverlimits und robots.txt-Regeln können Ergebnisse unvollständig machen'], privacyTitle: 'Datenschutz', privacy: 'Es werden nur die von dir angegebene öffentliche URL und verbundene Sitemaps angefragt. Lokale Dateien werden nicht gelesen und Inhalte nicht als gehostetes Dokument gespeichert.', faqTitle: 'FAQ zum Sitemap-Prüfer', faqs: [{ question: 'Kann ich eine Website ohne robots.txt prüfen?', answer: 'Ja. Übliche Sitemap-Pfade werden weiter geprüft und das fehlende robots.txt wird angezeigt.' }, { question: 'Ist der Score ein Suchranking?', answer: 'Nein. Er fasst die auf dieser Seite beobachteten Probleme bei Zugriff, Struktur und URLs zusammen.' }, { question: 'Warum kann die URL-Anzahl unvollständig sein?', answer: 'Große Dateien, viele Unter-Sitemaps, Timeouts oder Serverlimits können einen Lauf begrenzen.' }], relatedTitle: 'Verwandte Werkzeuge', related: [{ label: 'Sitemap-Generator', path: '/sitemap-generator' }, { label: 'Sitemap-URL-Extraktor', path: '/sitemap-extractor' }],
    },
  },
  'sitemap-generator': {
    zh: {
      useTitle: 'Sitemap生成器怎么用', steps: [{ title: '选择生成方式', text: '抓取模式适合小型公开网站，粘贴模式适合已有完整URL清单的网站。' }, { title: '检查URL规则', text: '一个Sitemap中的URL必须属于同一网站来源，工具会删除锚点并去除重复地址。' }, { title: '下载并部署', text: '生成后先用Sitemap验证器检查，再把sitemap.xml放到网站公开路径并提交搜索引擎。' }], exampleTitle: '输入和输出示例', inputLabel: '输入方式', inputExample: '抓取：https://example.com\n粘贴：https://example.com/\n      https://example.com/about', outputLabel: '输出文件', outputExample: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>https://example.com/</loc></url>\n</urlset>', supportTitle: '支持范围', support: ['抓取模式：公开同源HTML页面，每次最多50页', '粘贴模式：最多50,000个URL，并限制为同一网站来源', '输出标准：sitemap.xml中的urlset、loc和可选lastmod', '可选择写入可靠的Last-Modified日期或手动日期'], limitsTitle: '限制条件', limits: ['生成器不会替代网站服务器上的定时更新，内容变化后需要重新生成或自动化部署', '抓取模式遵守robots.txt并拦截内网地址，不保证发现所有由JavaScript动态生成的链接', 'lastmod应当是真实更新时间，不要为了提高抓取频率随意填写'], privacyTitle: '隐私说明', privacy: '抓取模式只请求公开网页，粘贴模式只在浏览器中处理你输入的URL。生成的XML不会上传或托管在Herdown。', faqTitle: 'Sitemap生成FAQ', faqs: [{ question: '下载后怎么使用？', answer: '把sitemap.xml上传到网站公开路径，确认可以通过浏览器访问，再在搜索引擎站长工具中提交地址。' }, { question: '为什么抓取最多50页？', answer: '在线抓取需要控制请求速度和资源消耗。更大网站可以先导出URL，再使用粘贴模式。' }, { question: '需要给每个URL填写lastmod吗？', answer: '不需要。只有知道真实更新时间时才建议填写。' }], relatedTitle: '相关工具', related: [{ label: 'Sitemap检查器', path: '/sitemap-checker' }, { label: 'Sitemap验证器', path: '/sitemap-validator' }],
    },
    en: {
      useTitle: 'How to generate a sitemap', steps: [{ title: 'Choose a method', text: 'Crawl mode suits small public sites. Paste mode suits a site that already has a complete URL list.' }, { title: 'Check URL rules', text: 'All URLs in one sitemap must share an origin. Fragments and duplicates are removed.' }, { title: 'Download and deploy', text: 'Validate the result, place sitemap.xml at a public site path, and submit its URL to search tools.' }], exampleTitle: 'Input and output example', inputLabel: 'Input methods', inputExample: 'Crawl: https://example.com\nPaste: https://example.com/\n       https://example.com/about', outputLabel: 'Output file', outputExample: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>https://example.com/</loc></url>\n</urlset>', supportTitle: 'Supported scope', support: ['Crawl mode: public same-origin HTML pages, up to 50 pages per request', 'Paste mode: up to 50,000 URLs from one origin', 'Output: sitemap.xml with urlset, loc, and optional lastmod', 'Use a verified Last-Modified date or enter a manual date'], limitsTitle: 'Limitations', limits: ['The generator does not replace scheduled updates on your server. Regenerate or automate deployment when URLs change', 'Crawl mode respects robots.txt and blocks private networks. JavaScript-only links may not be discovered', 'lastmod should be a real modification date, not a value added to influence crawling'], privacyTitle: 'Privacy', privacy: 'Crawl mode requests public pages only. Paste mode processes your URL list in the browser. Generated XML is not uploaded or hosted by Herdown.', faqTitle: 'Sitemap generator FAQ', faqs: [{ question: 'How do I use the download?', answer: 'Upload sitemap.xml to a public path, confirm it opens in a browser, then submit its URL in a webmaster tool.' }, { question: 'Why is crawling limited to 50 pages?', answer: 'The public crawler controls request speed and resource use. Export a larger URL list and use paste mode.' }, { question: 'Does every URL need lastmod?', answer: 'No. Add it only when you know the real modification date.' }], relatedTitle: 'Related tools', related: [{ label: 'Sitemap checker', path: '/sitemap-checker' }, { label: 'Sitemap validator', path: '/sitemap-validator' }],
    },
    ja: {
      useTitle: 'Sitemapジェネレーターの使い方', steps: [{ title: '方法を選ぶ', text: '小規模な公開サイトには巡回、大量のURLがある場合は貼り付けを使います。' }, { title: 'URL規則を確認', text: '1つのSitemapのURLは同じサイトのoriginにそろえ、重複とアンカーを削除します。' }, { title: '保存して設置', text: '生成後に検証し、sitemap.xmlを公開パスへ置いて検索サービスへ送信します。' }], exampleTitle: '入力と出力の例', inputLabel: '入力方法', inputExample: '巡回：https://example.com\n貼り付け：https://example.com/\n            https://example.com/about', outputLabel: '出力ファイル', outputExample: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>https://example.com/</loc></url>\n</urlset>', supportTitle: '対応範囲', support: ['巡回：公開された同一originのHTMLを1回50ページまで', '貼り付け：同じoriginのURLを50,000件まで', '出力：urlset、loc、任意のlastmodを含むsitemap.xml', '信頼できるLast-Modifiedまたは手動の日付を利用できます'], limitsTitle: '制限', limits: ['サイト側の定期更新は行いません。URLが変わったら再生成または自動配置が必要です', '巡回はrobots.txtを守り、非公開ネットワークを遮断します。JavaScriptだけで生成されるリンクは見つからない場合があります', 'lastmodには実際の更新日だけを入力してください'], privacyTitle: 'プライバシー', privacy: '巡回は公開ページだけをリクエストします。貼り付けたURLはブラウザ内で処理し、XMLをHerdownへアップロードしません。', faqTitle: 'Sitemap生成FAQ', faqs: [{ question: 'ダウンロード後はどう使いますか？', answer: 'sitemap.xmlを公開パスへ置き、ブラウザで開けることを確認して検索サービスへ送信します。' }, { question: '巡回が50ページまでなのはなぜですか？', answer: '公開巡回の速度と負荷を制御するためです。大きなサイトはURL一覧を貼り付けてください。' }, { question: 'すべてのURLにlastmodが必要ですか？', answer: 'いいえ。実際の更新日が分かる場合だけ追加します。' }], relatedTitle: '関連ツール', related: [{ label: 'Sitemapチェッカー', path: '/sitemap-checker' }, { label: 'Sitemapバリデーター', path: '/sitemap-validator' }],
    },
    es: {
      useTitle: 'Cómo generar un Sitemap', steps: [{ title: 'Elegir método', text: 'El rastreo sirve para sitios públicos pequeños. Pegar sirve cuando ya tienes una lista completa de URLs.' }, { title: 'Comprobar las reglas', text: 'Todas las URLs deben pertenecer al mismo origen. Se eliminan fragmentos y duplicados.' }, { title: 'Descargar y publicar', text: 'Valida el resultado, coloca sitemap.xml en una ruta pública y envía su URL a las herramientas de búsqueda.' }], exampleTitle: 'Ejemplo de entrada y salida', inputLabel: 'Métodos de entrada', inputExample: 'Rastrear: https://example.com\nPegar: https://example.com/\n       https://example.com/about', outputLabel: 'Archivo de salida', outputExample: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>https://example.com/</loc></url>\n</urlset>', supportTitle: 'Alcance', support: ['Rastreo: páginas HTML públicas del mismo origen, hasta 50 por solicitud', 'Pegado: hasta 50.000 URLs de un mismo origen', 'Salida: sitemap.xml con urlset, loc y lastmod opcional', 'Puedes usar una fecha Last-Modified verificada o una fecha manual'], limitsTitle: 'Limitaciones', limits: ['No sustituye las actualizaciones programadas del servidor. Regenera el archivo cuando cambien las URLs', 'Respeta robots.txt y bloquea redes privadas. Los enlaces generados solo con JavaScript pueden no aparecer', 'lastmod debe ser la fecha real de modificación'], privacyTitle: 'Privacidad', privacy: 'El rastreo solicita solo páginas públicas. El modo de pegado procesa las URLs en el navegador y el XML no se sube ni se aloja en Herdown.', faqTitle: 'Preguntas sobre el generador de Sitemap', faqs: [{ question: '¿Cómo uso el archivo descargado?', answer: 'Súbelo a una ruta pública, confirma que se abre en el navegador y envía su URL en una herramienta para webmasters.' }, { question: '¿Por qué el rastreo tiene un límite de 50 páginas?', answer: 'El rastreador público controla la velocidad y los recursos. Para sitios grandes, usa una lista pegada.' }, { question: '¿Cada URL necesita lastmod?', answer: 'No. Añádelo solo cuando conozcas la fecha real.' }], relatedTitle: 'Herramientas relacionadas', related: [{ label: 'Comprobador de Sitemap', path: '/sitemap-checker' }, { label: 'Validador de Sitemap', path: '/sitemap-validator' }],
    },
    de: {
      useTitle: 'Sitemap erzeugen', steps: [{ title: 'Methode wählen', text: 'Der Crawl eignet sich für kleine öffentliche Websites. Einfügen eignet sich für eine vollständige URL-Liste.' }, { title: 'URL-Regeln prüfen', text: 'Alle URLs müssen denselben Ursprung verwenden. Fragmente und Duplikate werden entfernt.' }, { title: 'Laden und veröffentlichen', text: 'Prüfe das Ergebnis, lege sitemap.xml an einem öffentlichen Pfad ab und reiche die URL bei Suchdiensten ein.' }], exampleTitle: 'Beispiel für Eingabe und Ausgabe', inputLabel: 'Eingabemethoden', inputExample: 'Crawl: https://example.com\nEinfügen: https://example.com/\n          https://example.com/about', outputLabel: 'Ausgabedatei', outputExample: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>https://example.com/</loc></url>\n</urlset>', supportTitle: 'Unterstützter Umfang', support: ['Crawl: öffentliche HTML-Seiten desselben Ursprungs, bis zu 50 pro Anfrage', 'Einfügen: bis zu 50.000 URLs desselben Ursprungs', 'Ausgabe: sitemap.xml mit urlset, loc und optionalem lastmod', 'Verifiziertes Last-Modified-Datum oder ein manuelles Datum möglich'], limitsTitle: 'Einschränkungen', limits: ['Der Generator ersetzt keine geplanten Server-Updates. Bei URL-Änderungen muss die Datei neu erzeugt oder bereitgestellt werden', 'Der Crawl beachtet robots.txt und blockiert private Netzwerke. Nur per JavaScript erzeugte Links können fehlen', 'lastmod sollte das echte Änderungsdatum enthalten'], privacyTitle: 'Datenschutz', privacy: 'Der Crawl ruft nur öffentliche Seiten ab. Der Einfüge-Modus verarbeitet deine URL-Liste im Browser und lädt XML nicht zu Herdown hoch.', faqTitle: 'FAQ zum Sitemap-Generator', faqs: [{ question: 'Wie nutze ich die geladene Datei?', answer: 'Lade sitemap.xml an einen öffentlichen Pfad, prüfe den Browserzugriff und reiche die URL in einem Webmaster-Tool ein.' }, { question: 'Warum sind nur 50 Crawl-Seiten möglich?', answer: 'Der öffentliche Crawl begrenzt Geschwindigkeit und Ressourcen. Für größere Websites kannst du eine URL-Liste einfügen.' }, { question: 'Braucht jede URL lastmod?', answer: 'Nein. Füge es nur mit einem echten Änderungsdatum hinzu.' }], relatedTitle: 'Verwandte Werkzeuge', related: [{ label: 'Sitemap-Prüfer', path: '/sitemap-checker' }, { label: 'Sitemap-Validator', path: '/sitemap-validator' }],
    },
  },
  'markdown-viewer': {
    zh: {
      useTitle: 'MarkdownViewer怎么用', steps: [{ title: '打开或粘贴文件', text: '选择.md、.markdown或包含Markdown文件的ZIP，也可以直接编辑左侧内容。' }, { title: '检查实时预览', text: '右侧会同步显示标题、列表、表格、引用、代码、链接和图片等常见Markdown结构。' }, { title: '选择输出', text: '确认排版后，可以下载原始.md，或导出独立HTML和PDF。' }], exampleTitle: '输入和输出示例', inputLabel: '输入Markdown', inputExample: '# 产品说明\n\n## 功能\n\n- 本地预览\n- HTML导出\n\n| 格式 | 状态 |\n| --- | --- |\n| Markdown | 可用 |', outputLabel: '预览和导出', outputExample: '左侧：可编辑Markdown源文档\n右侧：实时渲染结果\n文件：herdown-markdown.md\n页面：markdown-viewer.html\n文档：markdown-viewer.pdf', supportTitle: '支持内容', support: ['文件：.md、.markdown和ZIP中的Markdown文件', '语法：标题、段落、列表、任务列表、表格、引用、链接、图片和代码块', '操作：实时预览、编辑、复制、下载Markdown、导出HTML和PDF', '图片：可通过本地文件匹配相对路径图片并在预览中显示'], limitsTitle: '限制条件', limits: ['复杂插件语法、动态图表和特定编辑器扩展可能不会完全渲染', 'PDF导出使用当前预览样式，外部字体和远程图片可能受浏览器权限影响', '本地自动保存只保留在当前浏览器，不等于云端备份'], privacyTitle: '隐私说明', privacy: '文件、编辑内容和自动保存草稿留在当前浏览器。页面不会把本地Markdown上传到Herdown服务器。', faqTitle: 'MarkdownViewerFAQ', faqs: [{ question: '支持拖入文件吗？', answer: '支持。可以拖入Markdown文件或包含Markdown文件的ZIP。' }, { question: '为什么图片没有显示？', answer: '相对路径图片需要同时选择对应图片文件，远程图片还可能受到站点防盗链或浏览器权限限制。' }, { question: '导出的HTML可以独立打开吗？', answer: '可以。导出的HTML包含渲染后的正文和基础样式，可直接保存和打开。' }], relatedTitle: '相关工具', related: [{ label: 'Markdown转HTML', path: '/markdown-to-html' }, { label: 'Markdown转PDF', path: '/markdown-to-pdf' }],
    },
    en: {
      useTitle: 'How to use Markdown Viewer', steps: [{ title: 'Open or paste a file', text: 'Choose a .md, .markdown, or ZIP file, or edit the Markdown directly in the left panel.' }, { title: 'Review the live preview', text: 'The right panel renders headings, lists, tables, quotes, code, links, and images as you edit.' }, { title: 'Choose an export', text: 'Download the original .md file or export the current preview as standalone HTML or PDF.' }], exampleTitle: 'Input and output example', inputLabel: 'Markdown input', inputExample: '# Product notes\n\n## Features\n\n- Local preview\n- HTML export\n\n| Format | Status |\n| --- | --- |\n| Markdown | Ready |', outputLabel: 'Preview and exports', outputExample: 'Left: editable Markdown source\nRight: live rendered preview\nFile: herdown-markdown.md\nPage: markdown-viewer.html\nDocument: markdown-viewer.pdf', supportTitle: 'Supported content', support: ['Files: .md, .markdown, and Markdown files inside ZIP archives', 'Syntax: headings, paragraphs, lists, tasks, tables, quotes, links, images, and code blocks', 'Actions: live preview, edit, copy, Markdown download, HTML and PDF export', 'Images: match local files to relative image references for preview'], limitsTitle: 'Limitations', limits: ['Plugin syntax, dynamic diagrams, and editor-specific extensions may not render completely', 'PDF export uses the current preview. External fonts and remote images may be limited by browser permissions', 'Autosave stays in this browser and is not a cloud backup'], privacyTitle: 'Privacy', privacy: 'Files, edits, and the autosaved draft stay in this browser. Local Markdown is not uploaded to Herdown.', faqTitle: 'Markdown Viewer FAQ', faqs: [{ question: 'Can I drop files into the page?', answer: 'Yes. Drop a Markdown file or a ZIP containing Markdown files.' }, { question: 'Why is an image missing?', answer: 'Select the local image used by a relative path. Remote images can also be blocked by hotlink protection or browser permissions.' }, { question: 'Can the exported HTML open by itself?', answer: 'Yes. The HTML includes the rendered article and basic styles so it can be saved and opened directly.' }], relatedTitle: 'Related tools', related: [{ label: 'Markdown to HTML', path: '/markdown-to-html' }, { label: 'Markdown to PDF', path: '/markdown-to-pdf' }],
    },
    ja: {
      useTitle: 'MarkdownViewerの使い方', steps: [{ title: 'ファイルを開く', text: '.md、.markdown、Markdownを含むZIPを選択するか、左側で直接編集します。' }, { title: 'プレビューを確認', text: '右側に見出し、リスト、表、引用、コード、リンク、画像をリアルタイム表示します。' }, { title: '出力を選ぶ', text: '元の.mdを保存するか、現在のプレビューをHTMLまたはPDFに書き出します。' }], exampleTitle: '入力と出力の例', inputLabel: 'Markdown入力', inputExample: '# 製品メモ\n\n## 機能\n\n- ローカルプレビュー\n- HTML出力\n\n| 形式 | 状態 |\n| --- | --- |\n| Markdown | 利用可能 |', outputLabel: 'プレビューと出力', outputExample: '左：編集できるMarkdown\n右：リアルタイムプレビュー\nファイル：herdown-markdown.md\nページ：markdown-viewer.html\n文書：markdown-viewer.pdf', supportTitle: '対応内容', support: ['ファイル：.md、.markdown、ZIP内のMarkdown', '構文：見出し、段落、リスト、タスク、表、引用、リンク、画像、コードブロック', '操作：プレビュー、編集、コピー、Markdown、HTML、PDF出力', '画像：相対パスに対応するローカル画像を選択して表示'], limitsTitle: '制限', limits: ['プラグイン構文、動的図表、特定エディターの拡張は完全に表示できない場合があります', 'PDFは現在のプレビューを使います。外部フォントや画像はブラウザの制限を受ける場合があります', '自動保存はこのブラウザだけに残り、クラウドバックアップではありません'], privacyTitle: 'プライバシー', privacy: 'ファイル、編集内容、自動保存はこのブラウザ内に残ります。ローカルMarkdownをHerdownへアップロードしません。', faqTitle: 'MarkdownViewerFAQ', faqs: [{ question: 'ファイルをドロップできますか？', answer: 'はい。MarkdownファイルまたはMarkdownを含むZIPをドロップできます。' }, { question: '画像が表示されないのはなぜですか？', answer: '相対パスの画像は対応する画像ファイルも選択してください。外部画像は防止設定やブラウザ権限の影響を受けます。' }, { question: 'HTMLは単独で開けますか？', answer: 'はい。出力HTMLには記事と基本スタイルが含まれます。' }], relatedTitle: '関連ツール', related: [{ label: 'MarkdownからHTML', path: '/markdown-to-html' }, { label: 'MarkdownからPDF', path: '/markdown-to-pdf' }],
    },
    es: {
      useTitle: 'Cómo usar Markdown Viewer', steps: [{ title: 'Abrir o pegar un archivo', text: 'Elige un archivo .md, .markdown o ZIP, o edita el Markdown directamente en el panel izquierdo.' }, { title: 'Revisar la vista previa', text: 'El panel derecho renderiza títulos, listas, tablas, citas, código, enlaces e imágenes mientras editas.' }, { title: 'Elegir una salida', text: 'Descarga el .md original o exporta la vista previa como HTML o PDF independiente.' }], exampleTitle: 'Ejemplo de entrada y salida', inputLabel: 'Entrada Markdown', inputExample: '# Notas del producto\n\n## Funciones\n\n- Vista local\n- Exportación HTML\n\n| Formato | Estado |\n| --- | --- |\n| Markdown | Listo |', outputLabel: 'Vista previa y exportaciones', outputExample: 'Izquierda: fuente Markdown editable\nDerecha: vista renderizada\nArchivo: herdown-markdown.md\nPágina: markdown-viewer.html\nDocumento: markdown-viewer.pdf', supportTitle: 'Contenido compatible', support: ['Archivos: .md, .markdown y Markdown dentro de ZIP', 'Sintaxis: títulos, párrafos, listas, tareas, tablas, citas, enlaces, imágenes y código', 'Acciones: vista previa, edición, copia, descarga Markdown y exportación HTML o PDF', 'Imágenes: relaciona archivos locales con referencias relativas'], limitsTitle: 'Limitaciones', limits: ['La sintaxis de plugins, diagramas dinámicos y extensiones de editores puede no renderizarse por completo', 'El PDF usa la vista actual. Las fuentes y las imágenes remotas dependen de los permisos del navegador', 'El guardado automático permanece en este navegador y no es una copia en la nube'], privacyTitle: 'Privacidad', privacy: 'Los archivos, cambios y borradores automáticos permanecen en este navegador. El Markdown local no se sube a Herdown.', faqTitle: 'Preguntas sobre Markdown Viewer', faqs: [{ question: '¿Puedo arrastrar archivos?', answer: 'Sí. Arrastra un Markdown o un ZIP que contenga archivos Markdown.' }, { question: '¿Por qué falta una imagen?', answer: 'Selecciona también la imagen local usada por la ruta relativa. Las imágenes remotas pueden estar bloqueadas.' }, { question: '¿El HTML exportado funciona solo?', answer: 'Sí. Incluye el artículo renderizado y estilos básicos para guardarlo y abrirlo.' }], relatedTitle: 'Herramientas relacionadas', related: [{ label: 'Markdown a HTML', path: '/markdown-to-html' }, { label: 'Markdown a PDF', path: '/markdown-to-pdf' }],
    },
    de: {
      useTitle: 'Markdown Viewer verwenden', steps: [{ title: 'Datei öffnen oder einfügen', text: 'Wähle .md, .markdown oder ein ZIP und bearbeite den Markdown-Text links direkt.' }, { title: 'Live-Vorschau prüfen', text: 'Rechts werden Überschriften, Listen, Tabellen, Zitate, Code, Links und Bilder beim Bearbeiten gerendert.' }, { title: 'Ausgabe wählen', text: 'Lade die ursprüngliche .md-Datei oder die aktuelle Vorschau als HTML oder PDF.' }], exampleTitle: 'Beispiel für Eingabe und Ausgabe', inputLabel: 'Markdown-Eingabe', inputExample: '# Produktnotizen\n\n## Funktionen\n\n- Lokale Vorschau\n- HTML-Export\n\n| Format | Status |\n| --- | --- |\n| Markdown | Bereit |', outputLabel: 'Vorschau und Exporte', outputExample: 'Links: bearbeitbarer Markdown\nRechts: Live-Vorschau\nDatei: herdown-markdown.md\nSeite: markdown-viewer.html\nDokument: markdown-viewer.pdf', supportTitle: 'Unterstützte Inhalte', support: ['Dateien: .md, .markdown und Markdown in ZIP-Archiven', 'Syntax: Überschriften, Absätze, Listen, Aufgaben, Tabellen, Zitate, Links, Bilder und Codeblöcke', 'Aktionen: Vorschau, Bearbeiten, Kopieren, Markdown-Download, HTML- und PDF-Export', 'Bilder: Lokale Dateien mit relativen Bildpfaden verknüpfen'], limitsTitle: 'Einschränkungen', limits: ['Plugin-Syntax, dynamische Diagramme und editorbezogene Erweiterungen werden eventuell nicht vollständig gerendert', 'Der PDF-Export nutzt die aktuelle Vorschau. Externe Schriften und Bilder können durch Browserrechte begrenzt sein', 'Die automatische Speicherung bleibt im Browser und ist kein Cloud-Backup'], privacyTitle: 'Datenschutz', privacy: 'Dateien, Änderungen und Entwürfe bleiben in diesem Browser. Lokaler Markdown wird nicht zu Herdown hochgeladen.', faqTitle: 'FAQ zum Markdown Viewer', faqs: [{ question: 'Kann ich Dateien hineinziehen?', answer: 'Ja. Ziehe eine Markdown-Datei oder ein ZIP mit Markdown-Dateien hinein.' }, { question: 'Warum fehlt ein Bild?', answer: 'Wähle bei einem relativen Pfad auch die lokale Bilddatei aus. Remote-Bilder können blockiert werden.' }, { question: 'Kann die exportierte HTML-Datei allein geöffnet werden?', answer: 'Ja. Sie enthält den gerenderten Artikel und grundlegende Styles.' }], relatedTitle: 'Verwandte Werkzeuge', related: [{ label: 'Markdown zu HTML', path: '/markdown-to-html' }, { label: 'Markdown zu PDF', path: '/markdown-to-pdf' }],
    },
  },
  'pdf-to-markdown': {
    zh: {
      useTitle: '文字型PDF转Markdown怎么用', steps: [{ title: '选择PDF', text: '拖入或选择能够复制文字的PDF，页面会在当前浏览器中逐页提取文字。' }, { title: '检查结构', text: '输出会生成YAML信息、文档标题和按页划分的H2小节，便于继续编辑。' }, { title: '复制或下载', text: '确认结果没有缺页或错位后，复制Markdown或下载.md文件。' }], exampleTitle: '输入和输出示例', inputLabel: '输入文件', inputExample: '产品手册.pdf\n文字型PDF，可选择文字', outputLabel: '输出Markdown', outputExample: '---\ntitle: "产品手册"\nfile_type: "text-pdf"\npage_count: 8\n---\n\n# 产品手册\n\n## 第1页\n\n正文内容...', supportTitle: '支持格式和适用场景', support: ['输入格式：文字型.pdf', '输出格式：带YAML信息和分页标题的.md', '适合报告、论文、说明书、合同和可复制文字的资料', '文件在浏览器中处理，不需要上传'], limitsTitle: '限制条件', limits: ['扫描版、图片型和没有可选文字的PDF不能在线转换，请使用本地Unlimited-OCRSkill', '多栏排版、复杂表格、脚注、公式和图文混排可能需要人工复核', '加密、需要密码或损坏的PDF可能无法读取，图片不会自动变成OCR文字'], privacyTitle: '隐私说明', privacy: 'PDF只在当前浏览器中读取，转换结果也只在当前页面生成。文件内容不会上传到Herdown服务器。', faqTitle: 'PDF转MarkdownFAQ', faqs: [{ question: '扫描PDF为什么不能在线处理？', answer: '扫描PDF通常只有图片，没有可选择的文字。当前页面不调用在线OCR，避免把文件上传处理；请使用本地Unlimited-OCRSkill。' }, { question: '输出会保留原PDF排版吗？', answer: '会保留文字顺序和分页结构，但Markdown不是固定版式，复杂视觉布局需要人工整理。' }, { question: '生成的Markdown包含哪些信息？', answer: '包含文件名、文件类型、页数、文档标题和按页整理的文字。' }], relatedTitle: '相关工具', related: [{ label: 'MarkdownViewer', path: '/markdown-viewer' }, { label: 'Word转Markdown', path: '/word-to-markdown' }],
    },
    en: {
      useTitle: 'How to convert a text PDF to Markdown', steps: [{ title: 'Choose a PDF', text: 'Drop or choose a PDF with selectable text. The browser extracts text page by page.' }, { title: 'Review the structure', text: 'The output includes YAML metadata, a document title, and page sections using H2 headings.' }, { title: 'Copy or download', text: 'Check for missing pages or layout issues, then copy the Markdown or download the .md file.' }], exampleTitle: 'Input and output example', inputLabel: 'Input file', inputExample: 'product-manual.pdf\nText-based PDF with selectable text', outputLabel: 'Markdown output', outputExample: '---\ntitle: "Product manual"\nfile_type: "text-pdf"\npage_count: 8\n---\n\n# Product manual\n\n## Page 1\n\nExtracted text...', supportTitle: 'Supported format and use cases', support: ['Input: text-based .pdf', 'Output: .md with YAML metadata and page headings', 'Useful for reports, papers, manuals, contracts, and selectable text', 'Processing runs in the browser without an upload'], limitsTitle: 'Limitations', limits: ['Scanned, image-only, and non-selectable PDFs are not supported online. Use the local Unlimited-OCRSkill', 'Multi-column layouts, complex tables, footnotes, formulas, and mixed image layouts may need review', 'Encrypted or damaged PDFs may fail, and images are not automatically converted into OCR text'], privacyTitle: 'Privacy', privacy: 'The PDF is read in this browser, and the result is generated on this page. File content is not uploaded to Herdown.', faqTitle: 'PDF to Markdown FAQ', faqs: [{ question: 'Why are scanned PDFs not supported online?', answer: 'A scan usually contains images instead of selectable text. This page does not call online OCR, so use the local Unlimited-OCRSkill.' }, { question: 'Will the original PDF layout be preserved?', answer: 'Text order and page sections are preserved where possible. Markdown does not preserve fixed visual layout, so complex designs need review.' }, { question: 'What does the Markdown include?', answer: 'It includes the file name, file type, page count, document title, and extracted text organized by page.' }], relatedTitle: 'Related tools', related: [{ label: 'Markdown Viewer', path: '/markdown-viewer' }, { label: 'Word to Markdown', path: '/word-to-markdown' }],
    },
    ja: {
      useTitle: 'テキストPDFをMarkdownに変換する方法', steps: [{ title: 'PDFを選択', text: '文字を選択できるPDFをドロップまたは選択し、ページごとに文字を抽出します。' }, { title: '構造を確認', text: 'YAML情報、タイトル、ページごとのH2見出しを含むMarkdownを生成します。' }, { title: 'コピーまたは保存', text: '欠落や崩れがないか確認してからMarkdownをコピーまたは.mdで保存します。' }], exampleTitle: '入力と出力の例', inputLabel: '入力ファイル', inputExample: '製品マニュアル.pdf\n文字を選択できるPDF', outputLabel: 'Markdown出力', outputExample: '---\ntitle: "製品マニュアル"\nfile_type: "text-pdf"\npage_count: 8\n---\n\n# 製品マニュアル\n\n## 1ページ\n\n抽出された本文...', supportTitle: '対応形式と用途', support: ['入力形式：テキストPDFの.pdf', '出力形式：YAML情報とページ見出し付き.md', 'レポート、論文、マニュアル、契約書に利用できます', 'アップロードせずブラウザ内で処理します'], limitsTitle: '制限', limits: ['スキャンや画像だけのPDFはオンライン非対応です。ローカルのUnlimited-OCRSkillを使ってください', '段組み、複雑な表、脚注、数式、画像混在は確認が必要な場合があります', '暗号化PDFは読み取れない場合があり、画像を自動OCRしません'], privacyTitle: 'プライバシー', privacy: 'PDFはこのブラウザで読み取り、結果もこのページで生成します。内容をHerdownへアップロードしません。', faqTitle: 'PDFからMarkdownFAQ', faqs: [{ question: 'スキャンPDFに対応しないのはなぜですか？', answer: 'スキャンPDFは選択できる文字ではなく画像を含むことが多いためです。オンラインOCRを使わず、ローカルのUnlimited-OCRSkillを案内しています。' }, { question: '元のレイアウトは保持されますか？', answer: '文字の順番とページ構造は可能な範囲で保持しますが、固定レイアウトはMarkdownにそのまま移りません。' }, { question: '出力に何が含まれますか？', answer: 'ファイル名、形式、ページ数、タイトル、ページごとの抽出テキストが含まれます。' }], relatedTitle: '関連ツール', related: [{ label: 'MarkdownViewer', path: '/markdown-viewer' }, { label: 'WordからMarkdown', path: '/word-to-markdown' }],
    },
    es: {
      useTitle: 'Cómo convertir un PDF de texto a Markdown', steps: [{ title: 'Elegir el PDF', text: 'Suelta o elige un PDF con texto seleccionable. El navegador extrae el texto página a página.' }, { title: 'Revisar la estructura', text: 'La salida incluye metadatos YAML, título y secciones por página con encabezados H2.' }, { title: 'Copiar o descargar', text: 'Comprueba que no falten páginas y copia el Markdown o descarga el archivo .md.' }], exampleTitle: 'Ejemplo de entrada y salida', inputLabel: 'Archivo de entrada', inputExample: 'manual-producto.pdf\nPDF de texto seleccionable', outputLabel: 'Salida Markdown', outputExample: '---\ntitle: "Manual de producto"\nfile_type: "text-pdf"\npage_count: 8\n---\n\n# Manual de producto\n\n## Página 1\n\nTexto extraído...', supportTitle: 'Formato y usos', support: ['Entrada: .pdf de texto', 'Salida: .md con metadatos YAML y encabezados por página', 'Útil para informes, artículos, manuales, contratos y documentos con texto seleccionable', 'Se procesa en el navegador sin subir el archivo'], limitsTitle: 'Limitaciones', limits: ['Los PDF escaneados o solo de imagen no se admiten en línea. Usa Unlimited-OCRSkill local', 'Las columnas, tablas complejas, notas, fórmulas y diseños mixtos pueden necesitar revisión', 'Los PDF cifrados o dañados pueden fallar y las imágenes no se convierten automáticamente en OCR'], privacyTitle: 'Privacidad', privacy: 'El PDF se lee en este navegador y el resultado se genera en esta página. El contenido no se sube a Herdown.', faqTitle: 'Preguntas sobre PDF a Markdown', faqs: [{ question: '¿Por qué no se admiten PDF escaneados?', answer: 'Normalmente contienen imágenes en lugar de texto seleccionable. Esta página no usa OCR en línea; utiliza Unlimited-OCRSkill local.' }, { question: '¿Se conserva el diseño original?', answer: 'Se conserva el orden del texto y la estructura por páginas cuando es posible, pero Markdown no conserva una maquetación fija.' }, { question: '¿Qué incluye el Markdown?', answer: 'Incluye nombre, tipo, número de páginas, título y texto extraído organizado por página.' }], relatedTitle: 'Herramientas relacionadas', related: [{ label: 'Markdown Viewer', path: '/markdown-viewer' }, { label: 'Word a Markdown', path: '/word-to-markdown' }],
    },
    de: {
      useTitle: 'Textbasierte PDF in Markdown umwandeln', steps: [{ title: 'PDF auswählen', text: 'Wähle ein PDF mit markierbarem Text. Der Browser extrahiert den Text seitenweise.' }, { title: 'Struktur prüfen', text: 'Die Ausgabe enthält YAML-Metadaten, einen Titel und Seitenabschnitte mit H2-Überschriften.' }, { title: 'Kopieren oder laden', text: 'Prüfe fehlende Seiten oder Layoutprobleme und kopiere Markdown oder lade die .md-Datei.' }], exampleTitle: 'Beispiel für Eingabe und Ausgabe', inputLabel: 'Eingabedatei', inputExample: 'produkt-handbuch.pdf\nTextbasierte PDF mit markierbarem Text', outputLabel: 'Markdown-Ausgabe', outputExample: '---\ntitle: "Produkt-Handbuch"\nfile_type: "text-pdf"\npage_count: 8\n---\n\n# Produkt-Handbuch\n\n## Seite 1\n\nExtrahierter Text...', supportTitle: 'Format und Einsatz', support: ['Eingabe: textbasierte .pdf', 'Ausgabe: .md mit YAML-Metadaten und Seitenüberschriften', 'Geeignet für Berichte, Papers, Handbücher, Verträge und markierbaren Text', 'Verarbeitung im Browser ohne Upload'], limitsTitle: 'Einschränkungen', limits: ['Gescannte und bildbasierte PDFs werden online nicht unterstützt. Nutze das lokale Unlimited-OCRSkill', 'Mehrspaltenlayout, komplexe Tabellen, Fußnoten, Formeln und Bildmischungen müssen eventuell geprüft werden', 'Verschlüsselte oder beschädigte PDFs können fehlschlagen; Bilder werden nicht automatisch per OCR umgewandelt'], privacyTitle: 'Datenschutz', privacy: 'Die PDF wird in diesem Browser gelesen und das Ergebnis auf dieser Seite erzeugt. Der Dateiinhalt wird nicht zu Herdown hochgeladen.', faqTitle: 'FAQ zu PDF zu Markdown', faqs: [{ question: 'Warum werden Scans online nicht unterstützt?', answer: 'Scans enthalten meist Bilder statt markierbaren Text. Diese Seite verwendet kein Online-OCR; nutze das lokale Unlimited-OCRSkill.' }, { question: 'Bleibt das PDF-Layout erhalten?', answer: 'Textreihenfolge und Seitenstruktur werden möglichst erhalten. Markdown bildet kein festes visuelles Layout ab.' }, { question: 'Was enthält die Markdown-Datei?', answer: 'Dateiname, Dateityp, Seitenzahl, Dokumenttitel und nach Seiten geordneten Text.' }], relatedTitle: 'Verwandte Werkzeuge', related: [{ label: 'Markdown Viewer', path: '/markdown-viewer' }, { label: 'Word zu Markdown', path: '/word-to-markdown' }],
    },
  },
};

export function ToolSeoContent({ slug, language }: { slug: ToolSeoSlug; language: Language }) {
  const page = copy[slug]?.[language] || buildAdditionalToolSeoCopy(slug as AddedToolSeoSlug, language);
  const href = (path: string) => language === 'zh' ? path : `${path}?lang=${language}`;
  return (
    <section className="mt-10 space-y-8 border-t border-[#1e293b] pt-8" aria-labelledby={`${slug}-guide-title`}>
      <div className="max-w-3xl">
        <h2 id={`${slug}-guide-title`} className="text-2xl font-bold text-white">{page.useTitle}</h2>
        <ol className="mt-5 grid gap-4 md:grid-cols-3">
          {page.steps.map((step, index) => <li key={step.title} className="rounded-xl border border-[#1e293b] bg-[#0d131c] p-4"><span className="text-xs font-semibold text-emerald-400">{index + 1}</span><h3 className="mt-2 text-sm font-semibold text-white">{step.title}</h3><p className="mt-2 text-xs leading-6 text-slate-400">{step.text}</p></li>)}
        </ol>
      </div>

      <section aria-labelledby={`${slug}-example-title`} className="space-y-4">
        <h2 id={`${slug}-example-title`} className="text-xl font-bold text-white">{page.exampleTitle}</h2>
        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-xl border border-[#1e293b] bg-[#0d131c] p-4"><h3 className="text-sm font-semibold text-white">{page.inputLabel}</h3><pre className="mt-3 min-h-28 overflow-x-auto whitespace-pre-wrap rounded-lg bg-[#090d12] p-3 text-xs leading-6 text-slate-300">{page.inputExample}</pre></div>
          <div className="rounded-xl border border-[#1e293b] bg-[#0d131c] p-4"><h3 className="text-sm font-semibold text-white">{page.outputLabel}</h3><pre className="mt-3 min-h-28 overflow-x-auto whitespace-pre-wrap rounded-lg bg-[#090d12] p-3 text-xs leading-6 text-emerald-200">{page.outputExample}</pre></div>
        </div>
      </section>

      <div className="grid gap-4 md:grid-cols-2">
        <section aria-labelledby={`${slug}-support-title`} className="rounded-xl border border-[#1e293b] bg-[#0d131c] p-5"><h2 id={`${slug}-support-title`} className="text-lg font-bold text-white">{page.supportTitle}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-400">{page.support.map(item => <li key={item}>{item}</li>)}</ul></section>
        <section aria-labelledby={`${slug}-limits-title`} className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-5"><h2 id={`${slug}-limits-title`} className="text-lg font-bold text-white">{page.limitsTitle}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-400">{page.limits.map(item => <li key={item}>{item}</li>)}</ul></section>
      </div>

      <section aria-labelledby={`${slug}-privacy-title`} className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-5"><h2 id={`${slug}-privacy-title`} className="text-lg font-bold text-white">{page.privacyTitle}</h2><p className="mt-2 text-sm leading-7 text-slate-300">{page.privacy}</p></section>

      <section aria-labelledby={`${slug}-faq-title`} className="space-y-4"><h2 id={`${slug}-faq-title`} className="text-xl font-bold text-white">{page.faqTitle}</h2><div className="grid gap-3 md:grid-cols-3">{page.faqs.map(item => <article key={item.question} className="rounded-xl border border-[#1e293b] bg-[#0d131c] p-4"><h3 className="text-sm font-semibold text-slate-200">{item.question}</h3><p className="mt-2 text-xs leading-6 text-slate-400">{item.answer}</p></article>)}</div></section>

      <nav aria-label={page.relatedTitle} className="flex flex-wrap gap-x-6 gap-y-2 border-t border-[#1e293b] pt-5 text-sm font-semibold"><span className="text-slate-400">{page.relatedTitle}</span>{page.related.map(item => <a key={item.path} href={href(item.path)} className="text-emerald-300 hover:text-emerald-200">{item.label}<span aria-hidden="true"> →</span></a>)}</nav>
    </section>
  );
}
